Make hairRenderObject visibility depends on RenderActorInstance.
aws-lumberyard-dev/o3de pull request #151
Opened 2021-07-15 02:45 UTC by amzn-rhhong

1. Add a visibility flag for hair object.
2. Stop all update the hair object when its not visible.
3. Hair object flag got updated each frame based on the render actor instance.
In the future if we want to support hair visibility separate from actor instance we could add a separate flag.
 
Signed-off-by: rhhong <rhhong@amazon.com>

2021-07-15 07:18 UTC, hershey5045 requested changes
Should we reflect the ActorRequestBus visibility function as well in ActorComponent::Reflect?

2021-07-15 07:19 UTC, hershey5045 approved these changes
Apart from my previous comment, looks good!

2021-07-15 23:47 UTC, Adi-Amazon commented on Gems/AtomTressFX/Code/Rendering/HairFeatureProcessor.cpp
>                      if (m_addDispatchEnabled)
why not adding the condition in this line rather than continue?

2021-07-15 23:53 UTC, Adi-Amazon requested changes
In general most of the change is good.
I'm not sure if I like 'visible' since it's about activity and so I'd like to see it changed to isActive / enabled or something along this line.
This brings me to the next point that is - you did not connect it to the actual activation by the component itself but only taken from the actor state.  Actor should actually NOT affect the hair as you might want to inspect the hair but not the actor, so actor component will be inactive but hair is active.

2021-07-15 23:54 UTC, Adi-Amazon commented on Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.h
> +            bool GetRenderActorVisible() const override;
the connection is not 1:1 so let's remove this connection.  Hair can be rendered if the actor is not visible but exists.

2021-07-15 23:56 UTC, Adi-Amazon commented on Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.cpp
> +        bool ActorComponent::GetRenderActorVisible() const
see my other remark - instead of this point, the connection should be to the component state and the in the entity 'visible' state (so the 'eye' icon in the editor and the 'Enable/Disable' state of the hair component itself.

2021-07-16 13:33 UTC, Adi-Amazon commented on Gems/AtomTressFX/Code/Components/HairComponentConfig.cpp
> +                        ->Field("RenderingSettings", &HairComponentConfig::m_enabled)
There should not need to be an added field - components have 'enable' / 'disable' when you right click on them in the drop menu - we need to connect to this and make sure we have the same criteria (so if the component is disabled, the hair is not visible)

2021-07-16 13:33 UTC, Adi-Amazon requested changes
One last change - the enable is not a request to add a flag to the component (no need to change version), but rather to use and existing mechanism.  The one that enables/disable components already

2021-07-16 21:45 UTC, Adi-Amazon commented on Gems/AtomTressFX/Code/Components/HairComponentController.cpp
> -
Not sure how this can work.
This code is all based on reference removal and as long as the feature processor has this pointer it can be either dangling (risky) or take ref (not good)

2021-07-19 06:28 UTC, amzn-rhhong commented
Did a few changes. Here are the breakdowns:
1. Hair asset now moved to hair config. This is more align to the component / controller / config pattern of ly. 
2. Store a previous hair assetId in the editor config, so we can separate the call from updating the asset and updating the configs.
3. HairRenderObject in the controller stores in a smart pointer.

Before this change, tressFX mainline has a critical issue. The hair render object actually not got destroyed properly when switch from editor to game mode, and also no new hair render object is created. So if you do a ctrl+g, although you are seeing an hair render object, it is actually a 'left-over' hair render object from the editor.

2021-07-27 13:10 UTC, Adi-Amazon commented on Gems/AtomTressFX/Code/Components/HairComponentController.cpp
> +                m_renderObject.reset();
This might be unsafe.
Let's have a short chat - since the GPU might still hold resources, setting it to nullptr might be a safer way to guarantee that it will be released via instancing mechanism when it goes to 0.

2021-07-27 13:13 UTC, Adi-Amazon requested changes
Please review my request - if the object might be used by the GPU (remember that this can take up to 3 frames), then force releasing it might be unsafe and even if not crashing in most cases, might do exactly that on occasions.

2021-08-03 17:13 UTC, Adi-Amazon approved these changes
Very good change overall!
Before merging in make sure that you are coordinated with @hershey5045 changes and the conflicts that I see here are carefully resolved.

2021-08-04 00:58 UTC, amzn-rhhong commented on Gems/AtomTressFX/Code/Components/HairComponentController.cpp
> +                m_renderObject.reset();
Actually I don't think there is any different by using Reset() vs = nullptr. I looked at the code and the implementation is the same. https://stackoverflow.com/questions/16151550/c11-when-clearing-shared-ptr-should-i-use-reset-or-set-to-nullptr (check this)
The hairrenderobject inherit from dataInstance and it support its own ref counting. If something is still holding on to it, reset the m_renderObject (which is a smart ptr) won't delete the object, just decrease the ref count.

2021-08-04 00:59 UTC, merged