Added saving functionality after painting in Component Mode
aws-lumberyard-dev/o3de pull request #158
Opened 2021-07-21 21:29 UTC by its-tn10

Users are now able to enter Component Mode for an Image Gradient component, paint with the existing paintbrush tool, and exit Component Mode with their changes saved to a separate .dds file stored under a folder called `ImageGradientOverride`. 

Exiting and re-loading the level will also reload and render the new changes; additionally, users can select another image asset to create a new image gradient paint layer to override later on.

Issues to think about from what I know so far --

- There is additional latency in painting with the paintbrush tool in comparison to [the previous PR](https://github.com/aws-lumberyard-dev/o3de/commit/64c4203cf785cb1f7d3f45c648c683a8f324669b).
- When users select another image asset to create a new image gradient paint layer to override later on, I am having to change both the runtime and editor configurations. This occurs within `EditorImageGradientComponent::OnCompositionChanged`, and is due to `ImageGradientComponent::Activate` and `ImageGradientComponent::Deactivate` being called before it.
- Questions to think about for the future is how to handle the attributes of an Image Gradient component when it is duplicated and painting on a moving entity. Additionally, painting on an image and exiting Component Mode would save the revisions on a separate .dds file, but you can potentially exit the level and O3DE without saving the configuration changes.

2021-07-22 13:59 UTC, hultonha reviewed
Had a quick look over and left some comments - I think you mentioned the performance had degraded with this changes so might be worth trying to profile it a bit to see where the time is being spent, could be useful to find out now rather than later 🙂

2021-07-22 13:59 UTC, hultonha commented on Code/Framework/AzToolsFramework/AzToolsFramework/Brushes/PaintBrushComponentRequestBus.h
> + */
I think this license header needs to be updated (can likely just check another file, think it should now be)

```
/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */
```

2021-07-22 13:59 UTC, hultonha commented on Code/Framework/AzToolsFramework/AzToolsFramework/Brushes/PaintBrushComponentRequestBus.h
> +        // PaintBrushComponentRequests interface...
nit: You don't need this comment here, it's only useful in the type you're overriding to show where it comes from - also prefer `// PaintBrushComponentRequestBus interface overrides ...` (so you name the bus itself not the interface, makes Ctrl-F to find it easier in the file as that's the name the type uses to override)

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
> +                    ->Attribute(AZ::Edit::Attributes::ChangeNotify, AZ::Edit::PropertyRefreshLevels::EntireTree)
question: Does this need to be `EntireTree`? Might be able to use a less destructive property refresh for this

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
> +            m_configuration.m_overrideAsset = asset;
standards: missing braces, they must always be included on a new line

```
if (m_configuration.m_imageAsset.GetId() == asset.GetId())
{
    m_configuration.m_imageAsset = asset;
}
else
{
    m_configuration.m_overrideAsset = asset;
}
```

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
> +            m_configuration.m_overrideAsset = asset;
standards (repeated)

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
> +            m_configuration.m_overrideAsset = asset;
standards (repeated) (also consider maybe moving this to a function as it's repeated a bunch of times

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
> +                sourceAsset = m_configuration.m_overrideAsset;
standards: missing braces

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
> +                sourceAsset = m_configuration.m_overrideAsset;
standards: missing braces

2021-07-22 13:59 UTC, hultonha commented on Code/Framework/AzToolsFramework/AzToolsFramework/Brushes/PaintBrushComponentRequestBus.h
> +        using BusIdType = AZ::EntityId;
question: Are we sure this wants to be `EntityId` or could we use `EntityComponentIdPair`?

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +            AzFramework::StringFunc::Path::Join(projectPath, relativePath.c_str(), fullPath, true, true);
question: It feels like there must already be a utility in the engine somewhere to do this sort of sanity check to get a valid path, I'd maybe ping @lumberyard-employee-dm to ask about it

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +            relativePath = "ImageGradientOverride/" + uuidString + "_gsi.dds";
suggestion: Might be better to use a format string here rather than string `+` operator

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +            relativePath = "ImageGradientOverride/" + uuidString + "_gsi.dds";
The reason is the above makes lots of temporaries and can be quite a bit slower

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +        AZStd::string filePath)
nit: This likely doesn't need to be on its own line and could be passed by const ref or by a `string_view` instead

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +        using namespace ImageProcessingAtom;
nit: Prefer to avoid using namespace, instead use a using declaration like `using ImageProcessingAtom::<type>`

2021-07-22 13:59 UTC, hultonha commented on Gems/GradientSignal/Code/Source/ImageAsset.cpp
> +
nit: Trailing white space 😛

2021-07-22 16:03 UTC, mbalfour-amzn commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +
All of this path manipulation logic would benefit from using the types in AZ::IO::Path instead of doing it fully as string manipulations.

2021-07-22 19:54 UTC, lumberyard-employee-dm requested changes

2021-07-22 19:54 UTC, lumberyard-employee-dm commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +        AZ::IO::FileIOBase::GetInstance()->ResolvePath("@devassets@", projectPath, AZ_MAX_PATH_LEN);
There are `ResolvePath` function overloads that can return or accept an AZ::IO::FixedMaxPath
```
virtual bool ResolvePath(AZ::IO::FixedMaxPath& resolvedPath, const AZ::IO::PathView& path) const = 0;
AZStd::optional<AZ::IO::FixedMaxPath> ResolvePath(const AZ::IO::PathView& path) const;
```

Furthermore this isn't the proper way to query the projectPath.

The proper way is to invoke `AZ::Utils::GetProjectPath()`
```suggestion
        AZ::IO::FixedMaxPath = AZ::Utils::GetProjectPath()
```

2021-07-22 19:54 UTC, lumberyard-employee-dm commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +            relativePath = "ImageGradientOverride/" + uuidString + "_gsi.dds";
We should be using AZ::IO::Path for appending paths.

```
auto uuidString = AZ::Uuid::CreateRandom().ToString<AZ::IO::FixedMaxPathString>()
uuidString += "gsi.dds";
relativePath = AZ::IO::FixedMaxPath("ImageGradientOverride") / uuidString;

2021-07-22 19:54 UTC, lumberyard-employee-dm commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +            };
This can be simplified to use the C++23 [contains](https://en.cppreference.com/w/cpp/string/basic_string_view/contains) function which has been implemented in AZStd
```suggestion
            auto invalidCharacters = [](char letter)
            {
                return AZStd::string_view(R"(:"'{}<>)").contains(letter);
            };
```

2021-07-22 19:54 UTC, lumberyard-employee-dm commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +            AzFramework::StringFunc::Path::Join(projectPath, relativePath.c_str(), fullPath, true, true);
The `AZ::StringFunc::Path` functions are deprecated, the AZ::IO::Path functois should be used instead.
i.e
```
AZ::IO::FixedMaxPath fullPath = projectPath / relativePath;
```

2021-07-22 19:54 UTC, lumberyard-employee-dm commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
> +        AZ::IO::SystemFile::CreateDir(overrideFolder.c_str());
This can use AZ::IO::Path::ParentPath to retrieve the full path to create a directory from.
```
AZ::IO::FixedMaxPath overrideFolder = fullPath.ParentPath();
AZ::IO::SystemFile::CreateDir(overrideFolder.c_str());
```

2021-07-22 19:54 UTC, lumberyard-employee-dm commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
> +        AZStd::string m_path = "";
Two things here.
1. Since a path is being store, I think you should use the type of AZ::IO::Path
2. Initialize a string class with `""` is a pessimization, It actually requires strlen to be invoked on the empty to validate that it is size 0, where the default constructor would know that information and avoid such a check
`inline this_type& assign(const_pointer ptr) { return assign(ptr, Traits::length(ptr)); }`

2021-07-22 21:31 UTC, its-tn10 commented on Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
> +                    ->Attribute(AZ::Edit::Attributes::ChangeNotify, AZ::Edit::PropertyRefreshLevels::EntireTree)
Don't think I really can? Tested it with `ValuesOnly` and `AttributesAndValues` and they don't seem to have the same functionality in what I'm trying to accomplish, which, in this case, is when the user toggles on or off to "use the override," should also change the visibility of the "Component Mode" button in `EditorImageGradientComponent`. Unless there's a workaround for this...?

2021-07-23 19:55 UTC, mbalfour-amzn commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
> +        void WriteOutputFile(const AZStd::string filePath);
Nit: const string& instead of const string.

2021-07-23 20:24 UTC, its-tn10 commented on Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
> +        AZStd::string m_path = "";
For now, using `AZ::IO::Path` does not actually render the path string correctly in the property editor, and will temporarily be an `AZStd::string` for serialization purposes.

2021-07-26 15:11 UTC, mbalfour-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Brushes/PaintBrushComponentRequestBus.h
> +    class PaintBrushComponentRequests : public AZ::EBusTraits
This should be named as a Notification bus, not a Request bus.  The paint brush is notifying outwards that it's time to save, as opposed to receiving a request to save.

2021-07-26 15:11 UTC, mbalfour-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Brushes/PaintBrushComponentRequestBus.h
> +        static const AZ::EBusHandlerPolicy HandlerPolicy = AZ::EBusHandlerPolicy::Single;
As a notification bus, it should also technically allow for multiple connections, not just one.

2021-07-26 17:02 UTC, mbalfour-amzn approved these changes

2021-07-29 08:30 UTC, hultonha commented on Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
> +                    ->Attribute(AZ::Edit::Attributes::ChangeNotify, AZ::Edit::PropertyRefreshLevels::EntireTree)
I see got you, thanks for checking to make sure 👍

2021-07-29 08:32 UTC, hultonha approved these changes
LGTM 🙂 Thanks for making the updates 👍

2021-07-29 14:13 UTC, merged