Update headers to latest legal-approved headers.
aws-lumberyard-dev/o3de pull request #165
Opened 2021-07-23 22:48 UTC by hershey5045

Notes:
- Do we plan to include any of the files in the external folder?

2021-07-27 17:02 UTC, Adi-Amazon commented on Gems/AtomTressFX/External/license.txt
> +#
Please contact Nick and involve me in this - I'm not sure that we can add this to an external file that is open source by another company and under different license.

2021-07-27 17:05 UTC, Adi-Amazon requested changes
Very important change.
Per several of my remarks - I believe that any file that was marked by AMD license cannot have our open source license and cannot be changed this way.
Please add Nick to this review and CC me on the any exchange

2021-07-27 17:05 UTC, Adi-Amazon commented on Gems/AtomTressFX/Tools/Maya/TressFX_Exporter.py
> +#
Same here - this file should follow the AMD license and Nick should be involved

2021-07-27 18:09 UTC, hershey5045 commented on Gems/AtomTressFX/External/license.txt
> +#
Do we plan to include files from the external folder?

2021-08-06 23:24 UTC, lawsonamzn approved these changes
It looks good to me.
We cannot _change_ the license on files by others but we can publish them again, with teh same license.  The AMD license is MIT.  publishing it as SPDX-License "(Apache-2.0 OR MIT) AND MIT" means you have to comply with both if you republish.

2021-08-06 23:24 UTC, lawsonamzn commented on Gems/AtomTressFX/External/CMakeLists.txt
>  #add_subdirectory(Code)
Whats up with this file?  It appears to be empty / commented out?  Why not delete it?

2021-08-09 17:18 UTC, Adi-Amazon approved these changes

2021-08-09 19:15 UTC, merged