Build initial Terrain Physics Collider component LYN-6414
aws-lumberyard-dev/o3de pull request #220
Opened 2021-09-13 12:44 UTC by sphrose

2021-09-13 15:07 UTC, mbalfour-amzn requested changes

2021-09-13 15:07 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        float heightScale = 0.1f;
The height scale will also need to get exposed via an API, or else the thing querying for height won't know what scale has been used.

2021-09-13 15:07 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(aznumeric_cast<int16_t>(height / heightScale));
Should the heights be getting adjusted based on the position of the physics box?  I think we'd want them to be relative to the center of the box, not absolute values in world space.

2021-09-13 15:07 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +        void GetHeights([[maybe_unused]] AZStd::vector<int16_t>& heights);
Shouldn't these be override?

2021-09-13 15:07 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +        void HeightfieldUpdated();
Might want to make everything here and below protected or private.

2021-09-13 15:07 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.h
> +        static constexpr const char* const s_viewportIcon = "Editor/Icons/Components/Viewport/TerrainLayerSpawner.svg";
Wrong description

2021-09-13 16:24 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(aznumeric_cast<int16_t>(height / heightScale));
I thought it made sense to leave them as absolute, as the collider is going to have to be repositioned to the correct x/z point somewhere along the line, and adjusting the y position at the same time seemed to make sense. Plus it would confuse the use of the height scale value( from a previous comment) if you're having to take the world center into account when using the values.

2021-09-13 18:36 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(aznumeric_cast<int16_t>(height / heightScale));
There are a couple of problems with leaving them as absolute:
1. Precision.  Imagine the terrain is 65536 meters up, but only varies its height by a few cm up and down from that value.  Since the heights are getting put into an int16, world space would force these to have 1 m (or worse) resolution on the height values.  Even if they get repositioned later, the precision has already been lost.
2. The absolute-to-relative conversion has to happen *somewhere*, since the physics system will spawn the heightfield as an entity as a position.  We already know what position that's at, so why not just make it relative right from the start?  This also makes it stay consistent with shapes, models, and anything else that's providing positional data in relative space.

2021-09-14 08:13 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(aznumeric_cast<int16_t>(height / heightScale));
Sorry, I misunderstood your original comment, that makes complete sense.

2021-09-14 08:23 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +#include <TerrainSystem/TerrainSystemBus.h>
Nope

2021-09-14 11:49 UTC, moraaar commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +} // namespace AzFramework
Wrong closure namespace comment -> `// namespace Physics`

2021-09-14 11:49 UTC, moraaar commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class HeightfieldProviderRequests : public AZ::ComponentBus
Please add a doxygen comment like with `HeightfieldProviderNotifications` describing the bus purpose.

2021-09-14 11:49 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +#include <SurfaceData/SurfaceDataSystemRequestBus.h>
Are all these headers needed here? Please do a pass to verify they are.

2021-09-14 11:49 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +        , private Physics::HeightfieldProviderRequestsBus::Handler
minor: It's inheriting these classes as private and then overriding its interface as protected. Maybe these could be inherited as protected to be consistent?

2021-09-14 11:49 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +        void GetHeights([[maybe_unused]] AZStd::vector<int16_t>& heights) override;
`[[maybe_unused]]` is not relevant here in declaration, move to definition (if `heights` is actually potentially not used there).

2021-09-14 11:49 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +        float m_heightScale;
To be save for future changes please initialize this to 0.0f here.

2021-09-14 11:49 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    bool TerrainPhysicsColliderComponent::ReadInConfig(const AZ::ComponentConfig* baseConfig)
question: when are `ReadInConfig` and `ReadOutConfig` called? I haven't seen these used yet in other components, when are they necessary to be written?

2021-09-14 11:49 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        gridHeight = aznumeric_cast<int32_t>((maxBounds.GetY() - minBounds.GetY()) / gridResolution.GetY());
minor: declare `gridWidth, gridHeight` in the same like they are assigned.

2021-09-14 11:49 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(aznumeric_cast<int16_t>((height - worldCenterZ) / m_heightScale));
I was wondering why to store `m_heightScale` as (1 / 256) for now to divide when applying the scale here. 

If this is trying to scale by a factor of 256, maybe the scale variable should have 256.f and here directly multiply?

2021-09-14 11:49 UTC, moraaar commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.h
> +        static constexpr const char* const s_helpUrl = "";
Seems like all this could be moved to the cpp under an anonymous namespace so they are local to the cpp and they also wouldn't need to be `static` anymore.

The name convention for constant names (even statics) is `UpperCamelCase`, you can remove the `s_` prefix.

2021-09-14 11:56 UTC, sphrose commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +} // namespace AzFramework
Oops, thanks.

2021-09-14 11:58 UTC, sphrose commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class HeightfieldProviderRequests : public AZ::ComponentBus
Done

2021-09-14 12:02 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +#include <SurfaceData/SurfaceDataSystemRequestBus.h>
Fixed

2021-09-14 12:03 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +        , private Physics::HeightfieldProviderRequestsBus::Handler
Done

2021-09-14 12:03 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +        void GetHeights([[maybe_unused]] AZStd::vector<int16_t>& heights) override;
Removed

2021-09-14 12:04 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +        float m_heightScale;
Done

2021-09-14 12:06 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    bool TerrainPhysicsColliderComponent::ReadInConfig(const AZ::ComponentConfig* baseConfig)
They're necessary to populate/save a config class, if using, at startup/teardown. Strictly speaking it's unnecessary here at the moment, but will be used once the component is expanded to handle the surface/material mapping.

2021-09-14 12:07 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        gridHeight = aznumeric_cast<int32_t>((maxBounds.GetY() - minBounds.GetY()) / gridResolution.GetY());
Done

2021-09-14 12:15 UTC, sphrose commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.h
> +        static constexpr const char* const s_helpUrl = "";
This was copied from all the other editor components in the gem (and several other gems) but I've changed it as I agree it's better this way.

2021-09-14 12:20 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(aznumeric_cast<int16_t>((height - worldCenterZ) / m_heightScale));
This is for scaling the float heights to an int16, we then get 8 bits of meters and 8 bits of fractional meters. Typing this has made me realize it should be a multiply, not a divide, so I've changed this.

2021-09-14 13:20 UTC, moraaar approved these changes
Thanks for covering the feedback. I've suggested a couple of minor things, but you've got the approval.

2021-09-14 13:20 UTC, moraaar commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class HeightfieldProviderRequests : public AZ::ComponentBus
Thanks for adding it. A final dot in the sentence is missing, necessary for Doxygen.

2021-09-14 13:20 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    constexpr float DefaultHeightScale = 1.f / 256.f;
It'd be great to put a comment of the purpose of this scale, which you commented in the PR mentions it's to get the height values to fix a certain type size (8 bits).

2021-09-14 13:20 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        float worldCenterZ = worldSize.GetCenter().GetZ();
`worldCenterZ` can be const.

2021-09-14 13:20 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        int32_t gridHeight = aznumeric_cast<int32_t>((maxBounds.GetY() - minBounds.GetY()) / gridResolution.GetY());
`gridWidth` and `gridHeight` can be const.

2021-09-14 13:20 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +            float y = row * gridResolution.GetY() + minBounds.GetY();
`y` can be const.

2021-09-14 13:20 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                float x = col * gridResolution.GetX() + minBounds.GetX();
`x` can be const.

2021-09-14 13:23 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +#include <SurfaceData/SurfaceDataSystemRequestBus.h>
Thanks!

2021-09-14 13:39 UTC, sphrose commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class HeightfieldProviderRequests : public AZ::ComponentBus
Fixed

2021-09-14 13:43 UTC, AMZN-AlexOteiza commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        heights.reserve(gridWidth * gridHeight);
since you are clearing the heights, there is no benefit of heights being a output parameter.
For more clear API I recommend to just make this:
`AZStd::vector<int16_t> TerrainPhysicsColliderComponent::GetHeights()`

2021-09-14 13:44 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        float worldCenterZ = worldSize.GetCenter().GetZ();
Done

2021-09-14 13:44 UTC, AMZN-AlexOteiza commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    float TerrainPhysicsColliderComponent::GetHeightScale()
Could these functions be const? I understand that they come from an EBus, but seems like it would be a bit more correct

2021-09-14 13:44 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        int32_t gridHeight = aznumeric_cast<int32_t>((maxBounds.GetY() - minBounds.GetY()) / gridResolution.GetY());
Done

2021-09-14 13:44 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +            float y = row * gridResolution.GetY() + minBounds.GetY();
Done

2021-09-14 13:45 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                float x = col * gridResolution.GetX() + minBounds.GetX();
Done

2021-09-14 13:47 UTC, AMZN-AlexOteiza commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
> +        BaseClassType::ReflectSubClass<EditorTerrainPhysicsColliderComponent, BaseClassType>(
Q: how does this work? Perhaps may help a little comment explaining this could help, since ReflectSubClass doesn't seem to be the typical reflection code

2021-09-14 13:51 UTC, sphrose commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
> +    static constexpr const char* const HelpUrl = "";
Seems reasonable, done.

2021-09-14 14:00 UTC, AMZN-AlexOteiza commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +        static void GetProvidedServices(AZ::ComponentDescriptor::DependencyArrayType& services);
super nit:
Space between AZ_COMPONENT and the static functions can enhance a bit the reading

2021-09-14 14:20 UTC, moraaar commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void OnHeightfieldDataChanged(
I think it makes sense not to force notifications to be implemented. If more are added in the future you want to allow the handler to listen to the notifications they want, not force to implement all of them. Now there is one, but it's very likely more notifications are added in the future.

2021-09-14 14:30 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void OnHeightfieldDataChanged(
Since this is a notification bus, it should be up to the listener to decide which notifications they want to listen to.  With this only being one function, I 100% agree it could be pure virtual, but if we ever add a second function, then they should both have a default implementation, so IMO may as well add it now.

2021-09-14 15:13 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +            gridResolution, &AzFramework::Terrain::TerrainDataRequests::GetTerrainGridResolution);
Nothing to do now, but just to let you know, on a future merge this method will change to "GetTerrainHeightQueryResolution".  I'm merging some redundant buses together, and it's starting to look like we're potentially going to have different query resolutions for different types of data, so I'll need to change this to a more specific name.

2021-09-14 15:13 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        heights.reserve(gridWidth * gridHeight);
The one potential benefit is that the caller has the ability to reuse the memory allocation across multiple calls.  As a return value, there's no option for reuse.  
Admittedly, this matters more in other terrain APIs, since this particular API isn't likely to see that pattern of reuse, so I don't feel strongly about keeping vs changing on this one.  But it's why we're doing it this way on all the other terrain APIs.

2021-09-14 15:13 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(aznumeric_cast<int16_t>((height - worldCenterZ) * m_heightScale));
This is the first time I've heard a concern about emplace_back().  Is this a hypothetical concern, or one that you've observed?  I generally tend towards using emplace_back() myself because I thought it did a better job of avoiding construction of temporaries.

2021-09-14 15:13 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
> +    static constexpr const char* const HelpUrl = "";
I'm not sure auto actually deduces the right type - I believe we want to make sure these turn into const char* instead of const char[X].  Can you verify that they're becoming char*?  (Sadly, I forget the exact rationale, I just remember agreeing with it when I read it :( )

2021-09-14 15:13 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
> +        BaseClassType::ReflectSubClass<EditorTerrainPhysicsColliderComponent, BaseClassType>(
Suggestion:
```
// Call ReflectSubClass in EditorWrappedComponentBase to handle all the boilerplate reflection.
```

2021-09-14 15:33 UTC, sphrose commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
> +    static constexpr const char* const HelpUrl = "";
I've had to revert this to its previous state as the EditorWrappedComponentBase code we're using depends on the s_ versions of the

2021-09-14 15:36 UTC, sphrose commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.h
> +        static constexpr const char* const s_helpUrl = "";
Having just tried to compile, it turns out that the EditorWrappedComponentBase code we're using needs these in the form I had them first :(

2021-09-14 15:51 UTC, sphrose commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
> +        BaseClassType::ReflectSubClass<EditorTerrainPhysicsColliderComponent, BaseClassType>(
Added a comment.

2021-09-14 15:52 UTC, sphrose commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void OnHeightfieldDataChanged(
Changed

2021-09-14 15:58 UTC, amzn-sean commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void OnHeightfieldDataChanged(
```AZ::Event``` might fit better here?

2021-09-14 16:18 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(aznumeric_cast<int16_t>((height - worldCenterZ) * m_heightScale));
Good point about the lossy_cast. It will always fit using the default scale, but if it ever gets changed it might not. I'll fix that.

2021-09-14 16:21 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
> +        static void GetProvidedServices(AZ::ComponentDescriptor::DependencyArrayType& services);
Done

2021-09-14 16:21 UTC, sphrose commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    //! Bus used to retrieve heightfield data from a PhysicsCollider
Fixed

2021-09-14 16:24 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    void TerrainPhysicsColliderComponent::HeightfieldUpdated()
I've gone for "NotifyListenersOfHeightfieldDataChange" unless anyone objects, as it seems to cover the functionality.

2021-09-14 16:27 UTC, sphrose commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void OnHeightfieldDataChanged(
I'll change it back to have a default implementation.

2021-09-14 16:33 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        heights.reserve(gridWidth * gridHeight);
Is there any benefit to having both?

2021-09-14 16:35 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    float TerrainPhysicsColliderComponent::GetHeightScale()
Changed

2021-09-14 16:40 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        heights.reserve(gridWidth * gridHeight);
Probably not, I'd just pick one or the other and run with it.

2021-09-14 17:12 UTC, amzn-sean commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class HeightfieldProviderRequests : public AZ::ComponentBus
can we also document the functions? We try to document the whole API for physics stuff

2021-09-14 17:14 UTC, amzn-sean commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        if (serialize)
nit: as serialize is only used in the if scope and the type is on the right side you can do this.
```
if( auto* serialize = azrtti_cast<AZ::SerializeContext*>(context))
```
There are some other locations you can do similar.

2021-09-14 17:28 UTC, amzn-sean commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        , m_heightScale(DefaultHeightScale)
question: should ```m_heightScale``` not be set from the configuration as well?
I'm not seeing where this is set outside the constructors. Can this be a constant and not a class member?

2021-09-14 17:30 UTC, amzn-sean commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        Physics::HeightfieldProviderRequestsBus::Handler::BusConnect(GetEntityId());
nit: you can store the entity id in a const var and use it in each BusConnect, instead of call ```GetEntityId()``` 3 times

2021-09-14 17:52 UTC, amzn-sean commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    }
question/potential bug: Is this going to send double ```OnHeightfieldDataChanged``` events?
```OnShapeChanged``` change reason can be for transform changes OR shape changes. The Transform changed reason can come from ```OnTransformChanged``` bus events.
if think in ```OnShapeChanged``` you only want to call ```HeightfieldUpdated()``` if the reason is not the transform.

2021-09-14 17:53 UTC, amzn-sean commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    AZ::Vector2 TerrainPhysicsColliderComponent::GetHeightfieldGridSpacing()
question: can this return a ```const&``` and the function be const?

2021-09-14 17:54 UTC, amzn-sean commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        AZ::Vector2 gridResolution = GetHeightfieldGridSpacing();
looks like ```gridResolution``` can be const

2021-09-14 18:07 UTC, amzn-sean commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.h
> +        : public LmbrCentral::EditorWrappedComponentBase<TerrainPhysicsColliderComponent, TerrainPhysicsColliderConfig>
question: Is there a need for this editor component if it doesn't have any additional functionality?

2021-09-14 18:34 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class HeightfieldProviderRequests : public AZ::ComponentBus
FWIW, this file overlaps with the one in https://github.com/aws-lumberyard-dev/o3de/pull/221 .  I believe it got documented there.

2021-09-14 18:41 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        , m_heightScale(DefaultHeightScale)
Right now, height scale is a constant, but we might want to change it to be dynamically calculated based on the range of heights in the data to preserve the maximum amount of precision.  For example, if the overlap of the Terrain AABB and the Terrain Physics Collider AABB is only 128 m high, we could scale by 512 instead of 256, giving us a precision of 1/512 m instead of 1/256 m.  IMO it wouldn't make sense to expose it on the configuration though, because I don't think there's a time when you would ever want to have anything worse than "the max possible precision", and it doesn't seem like fun to adjust the value by hand.

2021-09-14 18:43 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.h
> +        : public LmbrCentral::EditorWrappedComponentBase<TerrainPhysicsColliderComponent, TerrainPhysicsColliderConfig>
The editor component (via EditorWrappedComponentBase) implicitly provides all the mechanisms that allow the component to "run" while in the editor outside of game mode, by wrapping and spawning the runtime version of the component.

2021-09-14 18:45 UTC, mbalfour-amzn approved these changes

2021-09-15 07:12 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        if (serialize)
Done

2021-09-15 07:13 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        Physics::HeightfieldProviderRequestsBus::Handler::BusConnect(GetEntityId());
Done

2021-09-15 07:15 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    }
Good spot, changed.

2021-09-15 07:17 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    AZ::Vector2 TerrainPhysicsColliderComponent::GetHeightfieldGridSpacing()
Done

2021-09-15 07:18 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        AZ::Vector2 gridResolution = GetHeightfieldGridSpacing();
Done

2021-09-15 09:10 UTC, sphrose commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class HeightfieldProviderRequests : public AZ::ComponentBus
I've just merged with #221, I've changed the documentation to match my changes.

2021-09-15 09:43 UTC, amzn-sean commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +    AZ::Vector2 TerrainPhysicsColliderComponent::GetHeightfieldGridSpacing()
Ah! ya, sorry missed that this was an EBus function

2021-09-15 14:31 UTC, mbalfour-amzn requested changes

2021-09-15 14:31 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        maxBounds.SetY(maxBounds.GetY() + gridResolution.GetX() - fmodf(maxBounds.GetY(), gridResolution.GetY()));
FYI - i just wrote a similar thing in some height calculation code, and this is buggy for negative numbers, because fmodf returns a negative value in that case.  So -3.18 with a grid resolution of 1 will get (-3.18 - (-.18)) which will go to -3, which _doesn't_ contain the AABB bounds fully.  Ken pointed out the following logic does what we want for both positive and negative cases:
```
AZ::Vector2 minBounds = AZ::Vector2(bounds.GetMin()) / gridResolution;
const AZ::Vector2 delta = AZ::Vector2(
                    minBounds.GetX() - floor(minBounds.GetX()),
                    minBounds.GetY() - floor(minBounds.GetY()));

minBounds = (minBounds - delta) * gridResolution;
```
(Side note - we might want to put this math into some sort of terrain utils file, feels like we're gonna use it a few times)

2021-09-15 14:31 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heightMaterials.emplace_back(point);
Suggestion:  If you pass in a bool terrainExists instead of a nullptr, you could fill in whether or not it's a hole on the HeightMaterialPoint by setting the material to Hole anywhere terrainExists is false.

2021-09-15 15:25 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heightMaterials.emplace_back(point);
I'll add the var in  now - I was leaving that until we got to the adding materials bit.

2021-09-15 15:26 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +        maxBounds.SetY(maxBounds.GetY() + gridResolution.GetX() - fmodf(maxBounds.GetY(), gridResolution.GetY()));
Done

2021-09-15 16:01 UTC, mbalfour-amzn approved these changes

2021-09-15 16:01 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +            0
Nit: 0.0f

2021-09-15 16:03 UTC, sphrose commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +            0
Fixed

2021-09-16 10:14 UTC, merged