Terrain/jjjoness/create initial generic api #6413
aws-lumberyard-dev/o3de pull request #221
Opened 2021-09-13 13:15 UTC by jjjoness

2021-09-13 15:24 UTC, mbalfour-amzn requested changes

2021-09-13 15:24 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    };
Doesn't need to be addressed now, but we should think about a better way to handle those two materialIndex fields.  We might want some sort of BitAndByte structure similar to PhysX to make the usage a little cleaner and more foolproof.

2021-09-13 15:24 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void UpdateHeightsAndMaterials(const AZ::Aabb& dirtyRegion, AZStd::vector<HeightMaterialPoint>& heights) = 0;
A few notes:
1. We *could* skip the "AsFloats" / "AsUint8" for now, since we don't have anything that will use them yet.
2. This will need an API for getting the height scale.
3. The APIs here should have doc comments describing what they do.
3. We should give the UpdateHeights APIs a bit more thought, both in terms of naming (possibly "GetHeightsInRegion"?), and in how its used - would the heights vector get partially overwritten?  Would it return a smaller box of values that maps to the dirtyRegion?  Might want to leave these out until they're getting implemented, to see what's needed by the implementation.

2021-09-13 15:24 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +
Mentioned on the other PR, but this hopefully shouldn't be needed.

2021-09-13 15:24 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.cpp
> +
This shouldn't use the cachedNativeMesh API, since we're not caching a native mesh, we're caching a heightfield.  We should have a new API for creating / releasing native heightfields.

2021-09-13 15:24 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.cpp
> +        m_dimensions = other.m_dimensions;
I'm not quite sure what needs to be on the shape configuration, but dimensions doesn't feel right.  Probably something that more closely resembles the heightfield parameters - array sizes in width and height, the height scale, etc.

2021-09-14 10:34 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    };
Added a new class to to handle this.

2021-09-14 10:56 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void UpdateHeightsAndMaterials(const AZ::Aabb& dirtyRegion, AZStd::vector<HeightMaterialPoint>& heights) = 0;
Removed the unused AsFloats and asUint8.
Added a Heightscale API.
Documented the APIs.
There are a few extra APIs I had thought of, but needed to get a provisional version in to be used by the remaining tasks. It was assumed these would be added as needed in those tasks.

2021-09-14 12:56 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.cpp
> +
DOne.

2021-09-14 12:56 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +
Removed.

2021-09-14 12:59 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.cpp
> +        m_dimensions = other.m_dimensions;
Shouldn't this be the size of the AxisAlignedBoxShape?

2021-09-14 15:19 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.cpp
> +        m_dimensions = other.m_dimensions;
The configuration should be whatever is needed to serialize and use the shape type.  The dimensions don't really need to be serialized, since technically heightfields don't care about the AABB size, they care about the number of grid points in X and Y.  And since all the data is really coming from other entities that have _their_ data serialized, it's possible that really all that's needed here is the entity ID describing where the heightfield data is coming from.

2021-09-14 15:27 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void GetHeightfieldGridSize(int32_t& nulColumns, int32_t& numRows) = 0;
"nulColumns" -> "numColumns"

2021-09-14 15:27 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        /// @return Vector containing Rows Spacing, Column Spacing.
Nit: Should this be "column spacing, row spacing"?  Doesn't the column spacing appear in the first value, and row in the second?

2021-09-14 15:27 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        /// @param heightScale contains all the heights in the height field.
"heightScale contains the scale of the height values returned by GetHeights".  It doesn't actually contain all the heights itself. :P

2021-09-14 15:28 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.cpp
> +        m_dimensions = other.m_dimensions;
Removed the unnecessary dimensions as the EntityID is already stored.

2021-09-14 15:33 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        /// @return Vector containing Rows Spacing, Column Spacing.
Changed.

2021-09-14 15:35 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        /// @param heightScale contains all the heights in the height field.
Changed.

2021-09-14 15:42 UTC, mbalfour-amzn approved these changes

2021-09-14 16:17 UTC, sphrose approved these changes

2021-09-14 16:27 UTC, merged

2021-09-14 18:16 UTC, amzn-sean commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class FlagAndUint7
please add documentation on the class + functions

2021-09-14 19:14 UTC, greerdv commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class FlagAndUint7
This feels like a very physx-specific thing as well. AzFramework/Physics is intended to be agnostic to the physics backend.

2021-09-14 19:35 UTC, greerdv commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        operator uint8_t() const { return m_data & 0x7f; }
Not sure if we're still following the same coding standards, but it used to be frowned upon to not use new lines after braces, even for single line statements. Also, it was supposed to be discouraged to have implementations in header files rather than cpp, although that rule was ignored all the time.

2021-09-14 19:35 UTC, greerdv commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        FlagAndUint7 m_materialIndex0; // Flag is a tesselation flag specifying which way the triangles go for this quad
Again this seems very physx-specific - other engines might do things differently.

2021-09-14 19:37 UTC, greerdv commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void GetHeightfieldGridSize(int32_t& nulColumns, int32_t& numRows) = 0;
looks like a typo here, guessing the variable name should be numColumns

2021-09-14 19:38 UTC, greerdv commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        /// Returns the distance between each height in the map.
I think the //! style is preferred over /// now.

2021-09-14 20:27 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class FlagAndUint7
It's a "generic" version of a physx-specific thing.  Each physics engine has a slightly different subset of features that they support for heightfields.  Of the publicly-available APIs that I could find, PhysX is the only one that supports controlling triangle ordering, per-quad materials, and per-quad holes.  We could certainly make this more generic of a structure and _not_ match PhysX, but that would mean translating this data per-vertex between formats without any guarantee that the more generic structure is useful to any other physics API.  We could also directly use the PhysX-defined structures, but that means we would no longer have a generic physics API for manipulating heightfields.

2021-09-15 09:12 UTC, amzn-sean commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class FlagAndUint7
If this is a PhysX only thing, that conversion should happen internal to the PhysX gem. The API should pass the height map data, so the physics backend can transform that into the format required.

Example:
[terrain system] -> creates heightmap data, which is a set of 'vertex coords' + 'height values' + 'material ids and weights' + 'flags (isHole)'.
[terrain system] -> requests Physics to physicalize terrain and passes the above structure of data.
[physX gem terrain impl] -> takes data and reads it and creates the PhysX version. This is where we may convert the data to the FlagAndUint7 class.

The goal of the AzFramework Physics API layer is to be a data provider/facilitator rather then a 'generic' API. By focusing on data here, changes to the implementation don't typically cause changes to the AzFramework API. Like Example, maybe in PhysX 5 terrain can support more flags per vert then just 'is hole' like 'is soft ground' (like sand or snow, where you're expected to sink a bit into the ground). Now the Flag + uint7 class wouldn't be enough as there are 2 flags to consider.

2021-09-15 09:52 UTC, AMZN-AlexOteiza commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        operator uint8_t() const { return m_data & 0x7f; }
Implicit cast operators is a recipe for lots of inadvertent problems.
It's better to have a getter here instead

2021-09-15 10:25 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class FlagAndUint7
I'll discuss this with the team.

2021-09-15 10:28 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void GetHeightfieldGridSize(int32_t& nulColumns, int32_t& numRows) = 0;
fixed.

2021-09-15 10:28 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        /// Returns the distance between each height in the map.
Will fix.

2021-09-15 15:28 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class FlagAndUint7
I have concerns - I feel like we're heading into "speculative generality" territory, where we're making a more generic format that will perform worse for features that don't exist.  For example, why only provide 2 materials per quad?  Why not immediately provide per-pixel level of materials through an image map, in case PhysX N ever supports that as well?  Keep in mind that out of PhysX, Bullet, React, and ODE, only PhysX currently supports per-triangle materials and holes, so this structure as written already provides enough data for all four of those physics implementations.

However, I also agree that aligning exactly with the PhysX format makes the data harder to read and understand, as the bit flags and combined hole/material usage can be confusing.

As a path forward, we'll take a pass at making this structure more general.  It will likely expand from 32-bit to 64-bit in size, and require data conversions in the PhysX code.  However, if the data conversions start showing up in profiles as bottlenecks, we might need to revisit this topic.

2021-09-15 17:05 UTC, jjjoness commented
Re-opened to address review issues.

2021-09-16 13:02 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +    class FlagAndUint7
Removed the FlagsAndUint7 class and changed the HeightMaterialPoint to be more agnostic.