Changes to make Heightfield data more general purpose
aws-lumberyard-dev/o3de pull request #225
Opened 2021-09-16 13:30 UTC by jjjoness

Signed-off-by: John Jones-Steele <jjjoness@amazon.com>

2021-09-16 14:13 UTC, mbalfour-amzn requested changes

2021-09-16 14:13 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        uint8_t m_materialIndex1; // Flag is "reserved"
This could become 
```
QuadMeshType m_quadMeshType = SubdivideULToBR;  // By default, create two triangles like this |\| , where this point is in the upper left corner.
uint8_t m_materialIndex = 0;  // The surface material index for the upper left corner of this quad.
uint16_t m_padding = 0;  // available for future use.
```
One implication of this is that our surface material types are associated with vertices instead of triangles, which maps out a little nicer to how our terrain system is built.  But that means that for creating the PhysX data, there will need to be logic that looks at the QuadMeshType, gets the 3 surface types for each triangle, and somehow has to decide which one of the three should be applied to that triangle if they don't all match.

2021-09-16 14:13 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
>          virtual void GetMaterialList(AZStd::vector<MaterialId>& materialList) const = 0;
For consistency with the other APIs, this should probably return the material list instead of taking it in as a parameter.

2021-09-16 14:13 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
>          virtual float GetScale() const = 0;
This no longer makes sense, now that we're returning floats for heights.

2021-09-16 14:13 UTC, mbalfour-amzn commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
>          virtual AZStd::vector<HeightMaterialPoint> UpdateHeightsAndMaterials(const AZ::Aabb& dirtyRegion) const = 0;
These can stay for now, but I'm pretty sure they'll need to change once you try to use them.  Imagine you've got a 100x100 heightmap, and the Aabb is saying a 5x5 region needs to change.  To truly update the data in PhysX without doing a full rewrite, I think you'll need to know the following:
* Did the overall size of the heightmap change
* What's the size of the dirty region (width, height)
* What are the starting offsets of the dirty region
* What's the actual set of data to change

Right now, this just returns a set of data, which either implies a full heightfield rewrite (inefficient), or that it's going to need more information added to it later.  We don't have to address this till you try to use the API, but wanted to get you thinking about it...

2021-09-16 14:13 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(azlossy_cast<float>((height - worldCenterZ) * m_heightScale));
All of the height scale computations should move into the PhysX-specific code.  It doesn't really make sense to do any scaling calculations if they're all floats.

2021-09-16 15:24 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        HeightMapFlags_HoleMaterial = 1 << 1
Implemented.

2021-09-16 15:24 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        uint8_t m_materialIndex1; // Flag is "reserved"
Implemented.

2021-09-16 15:25 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
>          virtual void GetMaterialList(AZStd::vector<MaterialId>& materialList) const = 0;
Changed.

2021-09-16 15:25 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
>          virtual float GetScale() const = 0;
Removed.

2021-09-16 15:25 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
>          virtual AZStd::vector<HeightMaterialPoint> UpdateHeightsAndMaterials(const AZ::Aabb& dirtyRegion) const = 0;
Noted.

2021-09-16 15:25 UTC, jjjoness commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(azlossy_cast<float>((height - worldCenterZ) * m_heightScale));
Changed.

2021-09-16 16:03 UTC, mbalfour-amzn approved these changes

2021-09-17 13:11 UTC, moraaar commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        Hole
Please add doxygen comments on this. Also, I don't know what UL and BL are, a comment beside it could be useful. If what they stand for it's not extremely long, the recommendation is to prefer long names to be explicit.

2021-09-17 13:11 UTC, moraaar commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        float m_height;
Please assign an initial value (0.0f) to be future proof that a value is going to be set.

2021-09-17 13:11 UTC, moraaar commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
>      struct HeightMaterialPoint
please add doxygen comments on the struct too. Also each member can use `//!<` to appear in doxygen format as well.

2021-09-17 13:11 UTC, moraaar commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void OnHeightfieldDataChanged( [[maybe_unused]] const AZ::Aabb& dirtyRegion)
nit: I think the convention is to not have an space between `(` and `[[`

2021-09-17 13:11 UTC, moraaar commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(azlossy_cast<float>(height - worldCenterZ));
It looks like now everything is `float`, can the `azlossy_cast` be removed?

2021-09-17 13:30 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        Hole
Comments added and UL and BL expanded.

2021-09-17 13:30 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        float m_height;
Done.

2021-09-17 13:33 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
>      struct HeightMaterialPoint
Done.

2021-09-17 13:33 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        virtual void OnHeightfieldDataChanged( [[maybe_unused]] const AZ::Aabb& dirtyRegion)
Done😀

2021-09-17 13:35 UTC, jjjoness commented on Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
> +                heights.emplace_back(azlossy_cast<float>(height - worldCenterZ));
I missed this, changed.

2021-09-17 14:06 UTC, moraaar approved these changes

2021-09-17 14:06 UTC, moraaar commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        SubdivideBottomLeftToUpperRight, //!< Subdivide the quad, from bottom left to upper right |/|, into two triangles
Missing dot at the end of the comment, necessary for doxygen as it's how it knows it's the main sentence, text after the first dot shows as detail.

Thanks for adding these, it's super clear now!

2021-09-17 14:07 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
> +        SubdivideBottomLeftToUpperRight, //!< Subdivide the quad, from bottom left to upper right |/|, into two triangles
You're welcome! Full stop added.

2021-09-17 14:20 UTC, merged