PhysicsCollider unit tests
aws-lumberyard-dev/o3de pull request #227
Opened 2021-09-16 16:09 UTC by sphrose

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +        ASSERT_TRUE(m_entity);
Please move the asset before calling `Init()`.

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    void AddPhysicsColliderAndShapeComponentToEntity()
There is already a physics collider component in the code base, maybe the name could be more explicit to avoid confusion and use TerrainPhysicsCollider.

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    }
This function is not the opposite of `CreateEntity`, so all the tests leave the pointer alive either until the next time `CreateEntity` is called or the fixture is destroyed. If this function is meant to be the "counter-function" of creation, this should destroy the pointer too doing `m_entity.reset();`.

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_NEAR(heightScale, 1.0f / 256.0f, 0.1f);
magic numbers. please set 1.0 / 256.0f to a const variable and 0.1f as well as the epsilon of error. Also 0.1f seems quick high, couldn't be lower?

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    float max = 1024.0f;
`min` and `max` can be `const`. Also, min and max are overused names in general, I suggest using more descriptive names.

Many of these const comments appear in several tests.

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    AZ::Vector2 mockHeightResolution = AZ::Vector2(1.0f);
`mockHeightResolution` can be const.

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    AZ::Aabb bounds = AZ::Aabb::CreateFromMinMax(AZ::Vector3(min), AZ::Vector3(max));
`bounds` can be const.

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    float regionMax = 512.0f;
`regionMax` can be const.

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(heights.size(), cols * rows);
Generally it's more secure to test the result with the value that it's actually expecting, rather than comparing it with the result of another internal operation. It could happen that it's the perfect storm and both results are the same but because both are wrong :)

There is nothing wrong comparing size if equal `cols * rows` but another check to compare the number is what is expected would make these tests more robust.

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    AZ::Aabb dirtyRegion = AZ::Aabb::CreateFromMinMax(AZ::Vector3(min), AZ::Vector3(regionMax));
`dirtyRegion` can be const.

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    ASSERT_TRUE(heights.size() != 0);
It's preferred to used the container function it provides to check it's not empty: `!heights.empty()`

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(heights[0], expectedHeight);
Similar comment as before, it's more robust to not rely on logic to check the test is successful. Just compare it with the number it's suppose to give.

2021-09-17 12:58 UTC, moraaar commented on Gems/Terrain/Code/Tests/TerrainMocks.h
> +    static const AZ::Uuid MockHeightfieldProviderNotificationBusListenerTypeId = "{2A89ED68-5937-4876-A073-FB6C8AF3D379}";
Could this be an static member of `MockTerrainDataRequestsListener`?

2021-09-17 13:40 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +        ASSERT_TRUE(m_entity);
Done

2021-09-17 14:35 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    }
I've changed this so that just Reset is called instead.

2021-09-17 14:37 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_NEAR(heightScale, 1.0f / 256.0f, 0.1f);
Done

2021-09-17 14:39 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    float max = 1024.0f;
Done

2021-09-17 14:41 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(heights.size(), cols * rows);
Done

2021-09-17 14:42 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    AZ::Aabb dirtyRegion = AZ::Aabb::CreateFromMinMax(AZ::Vector3(min), AZ::Vector3(regionMax));
Done

2021-09-17 14:42 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    ASSERT_TRUE(heights.size() != 0);
Done

2021-09-17 14:44 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(heights[0], expectedHeight);
Done

2021-09-17 14:51 UTC, sphrose commented on Gems/Terrain/Code/Tests/TerrainMocks.h
> +    static const AZ::Uuid MockHeightfieldProviderNotificationBusListenerTypeId = "{2A89ED68-5937-4876-A073-FB6C8AF3D379}";
AZ::Uuid can't have an in class initializer, but I've just removed the var and put the guid in directly.

2021-09-17 14:55 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    AZ::Vector2 mockHeightResolution = AZ::Vector2(1.0f);
Done

2021-09-17 14:55 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    AZ::Aabb bounds = AZ::Aabb::CreateFromMinMax(AZ::Vector3(min), AZ::Vector3(max));
Done

2021-09-17 14:55 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    float regionMax = 512.0f;
Done

2021-09-17 15:22 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    void AddPhysicsColliderAndShapeComponentToEntity()
I think this feedback applies across the whole file - "PhysicsColliderTests.cpp" would become "TerrainPhysicsColliderTests.cpp", the "PhysicsColliderComponentTest" class would become "TerrainPhysicsColliderComponentTest", etc...

2021-09-17 15:47 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(heights.size(), cols * rows);
@moraaar I disagree with this as a hard-and-fast rule.  Hard-coding a constant value now assumes that the math behind the hard-coded constant is correct, but with far less documentation as to how that constant was calculated.  In the worst-case scenario (which I've seen and fixed too many times already), it seems that people will run the function once for a set of inputs, write down the value, and use that as the "golden value" without validating its correctness.  It also means that changing constant column or row values at the top of the test requires a manual recalculation and change to the constant at the bottom of the test, so there's an opportunity for calculation errors on each manual change.  IMO, it's better to let the computer do the computing. :) 

I won't _block_ the PR if hard-coded constants are used, but I honestly think the calculation method is more secure, correct, and easier to maintain.

2021-09-17 15:52 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(heights[0], expectedHeight);
FWIW, this example is one where I can see using hard-coded values for the expected height, since it's using the exact same math for validation as the math inside the function being tested, and it's non-trivial math.  Ideally there would be comments next to the hard-coded values explaining the theoretical math used to achieve the hard-coded value though.

2021-09-17 16:30 UTC, mbalfour-amzn requested changes

2021-09-17 16:30 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    }
Suggestion:  This is a bit overkill, you could remove the class member and just have a single line that looks like this anywhere you're currently calling this method:
```
NiceMock<UnitTest::MockHeightfieldProviderNotificationBusListener> heightfieldBusListener;
```
There's no _harm_ in leaving it as-is, it just doesn't seem to provide any particular value.

2021-09-17 16:30 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(rows, 1024);
Please add some comments explaining why these are the right answers!

2021-09-17 16:30 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(rows, 1024);
Same here, please explain why this is correct.  In particular, for this one it would be worth calling out that incorrect would be 1023 if it doesn't expand the bounds.

2021-09-17 16:30 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(rows, 1024);
Same, here, please explain!

2021-09-17 16:30 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    const float boundsMax = 256;
Nit: 256.0f

2021-09-17 16:30 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +}
This test looks wrong - the entity isn't getting a transform set, and the bounds are 0-256, so I'm not sure what an expected height above 256 is supposed to produce.

2021-09-17 16:30 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/TerrainMocks.h
> +        AZ_COMPONENT(MockHeightfieldProviderNotificationBusListener, "{2A89ED68-5937-4876-A073-FB6C8AF3D379}")
This doesn't need to inherit from AZ::Component and have a UUID.  It could mock the ebus directly.

2021-09-17 17:14 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(heights.size(), cols * rows);
I was less worried about the simple math calculation, which I agree is fine to do (so long is not the same logic as the test is doing), but more about the fact that `cols` and `rows` (used to validate the result obtained from `GetHeights`) are obtained by calling about even (`GetHeightfieldGridSize`).

So if a future modification causes `GetHeights` to returns size 0 AND at the same time there is also an error that makes `GetHeightfieldGridSize` return `cols` and `rows` as 0 too, that means this test will pass, because the values are equal.

2021-09-20 08:15 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    }
Changed

2021-09-20 08:18 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(rows, 1024);
Done

2021-09-20 08:18 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(rows, 1024);
Done

2021-09-20 08:19 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(rows, 1024);
Done

2021-09-20 08:21 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    const float boundsMax = 256;
Fixed

2021-09-20 09:22 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +}
That's an interesting point, what should a heightfield contain if the height is outside the bounds?

2021-09-20 14:10 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(heights.size(), cols * rows);
Oh, great point.  This really should have some EXPECT_EQ calls to validate GetHeightfieldGridSize as well.

2021-09-20 14:51 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    EXPECT_EQ(heights.size(), cols * rows);
Added

2021-09-20 15:10 UTC, sphrose commented on Gems/Terrain/Code/Tests/TerrainMocks.h
> +        AZ_COMPONENT(MockHeightfieldProviderNotificationBusListener, "{2A89ED68-5937-4876-A073-FB6C8AF3D379}")
Fixed, and moved.

2021-09-20 15:37 UTC, sphrose commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +}
3a sounds reasonable: now that the heightfield has been changed to be floats rather than int16, and the scaling has been removed, should there be a replacement scale elsewhere, or is the float map staying all the way through?

2021-09-20 23:03 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +}
The replacement scale is going to be on the PhysX implementation side of things, since that's where we'll need to convert from floats to ints.

2021-09-20 23:08 UTC, mbalfour-amzn approved these changes

2021-09-20 23:08 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    // the values returned would by 1023.
Nit: "would by" -> "would be"

2021-09-20 23:08 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    // the values returned would by 1023.
"would by" -> "would be"

2021-09-20 23:08 UTC, mbalfour-amzn commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    EXPECT_EQ(heights.size(), expectedHeightsSize);
Since you're checking both cols and rows, I think it would be OK to just have the "cols * rows" check, and not _also_ need the expectedHeightsSize.  It doesn't hurt anything, but it feels a bit redundant.

2021-09-21 07:11 UTC, sphrose commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    // the values returned would by 1023.
Fixed

2021-09-21 07:11 UTC, sphrose commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    // the values returned would by 1023.
Fixed

2021-09-21 07:11 UTC, sphrose commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    EXPECT_EQ(heights.size(), expectedHeightsSize);
Removed

2021-09-21 11:23 UTC, moraaar commented on Gems/Terrain/Code/Tests/PhysicsColliderTests.cpp
> +    }
After the code change each test is now calling `m_entity->Reset();` which is reseting the entity, but it's still not destroying the pointer created by `CreateEntity`, for that it needs to call `m_entity.reset();`

2021-09-21 11:33 UTC, moraaar commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +        m_entity->GetId(), &Physics::HeightfieldProviderRequestsBus::Events::GetHeightfieldGridSize, cols, rows);
`cols, rows` are not used in the test anymore, please remove.

2021-09-21 11:33 UTC, moraaar commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    const int expectedHeightsSize = 1024 * 1024;
`expectedHeightsSize` is not used.

2021-09-21 11:33 UTC, moraaar commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +        m_entity->GetId(), &Physics::HeightfieldProviderRequestsBus::Events::GetHeightfieldGridSize, cols, rows);
Same, `cols, rows` are not used in the test anymore, please remove.

2021-09-21 11:33 UTC, moraaar commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    EXPECT_EQ(heights[0], expectedHeight);
These 3 lines could be removed since `heights[0]` is already checked in the next line comparing it to `expectedHeightValue`.

2021-09-21 13:13 UTC, sphrose commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    const int expectedHeightsSize = 1024 * 1024;
Done

2021-09-21 13:14 UTC, sphrose commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +        m_entity->GetId(), &Physics::HeightfieldProviderRequestsBus::Events::GetHeightfieldGridSize, cols, rows);
removed

2021-09-21 13:19 UTC, sphrose commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    EXPECT_EQ(heights[0], expectedHeight);
Removed

2021-09-21 17:45 UTC, moraaar reviewed
I only have this last comment about the entity unique pointer not being freed per test before giving the approval. Is there any reason not to free the pointer?

2021-09-21 17:45 UTC, moraaar commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    m_entity->Reset();
After the code change each test is now calling `m_entity->Reset();` which is reseting the entity, but it's still not destroying the pointer created by `CreateEntity`, for that it needs to call `m_entity.reset();`

2021-09-27 08:31 UTC, sphrose commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    m_entity->Reset();
Changed.

2021-09-27 15:20 UTC, moraaar approved these changes

2021-09-27 15:20 UTC, moraaar commented on Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> +    m_entity->Reset();
Missed resetting this entity. `m_entity.reset()`

2021-09-27 15:20 UTC, moraaar commented on Code/Framework/AzFramework/CMakeLists.txt
> +
nit: remove unnecessary spacing.

2021-09-27 15:20 UTC, moraaar commented on README.md
> +
Is this something you've changed in this PR?

2021-09-27 15:40 UTC, merged