{lyn5880} adding Instantiate Procedural Prefab to the Editor
aws-lumberyard-dev/o3de pull request #244
Opened 2021-09-28 18:05 UTC by jackalbe

Signed-off-by: jackalbe <23512001+jackalbe@users.noreply.github.com>

2021-09-28 18:35 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            }
This isn't finding the product asset in the cache folder. It's assuming that if the source asset isn't found at the path provided, then it'll be a product asset inside the cache folder. This is risky because if the source path is altered by mistake ( a typo or any other reason), then the path to the cache folder will be stored instead of path to the root project folder. Both paths are incorrect but the later at least says, 'I can't find your source path, so I'll try to mark your path as project root'. Your change will say ' I can't find the source path, so I'll treat it as a product asset'. 

Instead of doing it this way, we need an alternative to AssetSystemRequestBus::Events::GetSourceInfoBySourcePath where it fetches the product asset path. In that case, we can be confident that the path we store in the prefab is a valid path to a product asset.

2021-09-28 19:39 UTC, jackalbe commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            }
The source path is filled out by the asset builder, so a typo is not likely.

As an aside, the Prefabs should be considered Data so reading in Prefabs should never assert since they might have been hand coded JSON.

2021-09-28 20:29 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            }
Even if that's the case, assuming that the prefab will be in the product cache root folder if the source path is incorrect and not validating whether or not the prefab is present seems like it'll silently create prefabs with incorrect paths and lead to more user data bugs in the future. We should at least validate that the prefab is present when you modify the path of the nested prefab like this.

2021-09-28 21:08 UTC, jackalbe commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            }
AZ::IO::SystemFile::Exists() added

2021-09-29 14:02 UTC, amzn-mike requested changes

2021-09-29 14:28 UTC, jackalbe commented on Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
> +            return asset.BlockUntilLoadComplete() != AZ::Data::AssetData::AssetStatus::Error;
1/ asset.QueueLoad();
I can test it, but I have seen other code (like Atom) doing this. 

2/  hold on to the asset reference otherwise the AssetManager is free to cancel the load and release the asset.
Actually what really happens here: the data asset loads, adds the template DOM to the prefab system, and then releases. There is no reason (right now) to hold onto the asset. When we start looking at hot loading this process will likely change but then we need to decide what modules will hold the asset handles to respond to the hot loading logic.

3/ If you just need the path for the asset, you can use AssetSystemRequestBus::GetAssetInfoById
that might also be a solution here; all that really needs to happen is that the asset data (which contains a prefab JSON DOM) needs to be added to the Prefab system

2021-09-29 14:51 UTC, jackalbe commented on Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
> +            return asset.BlockUntilLoadComplete() != AZ::Data::AssetData::AssetStatus::Error;
class AssetInfo
{
public:
AZ::Data::AssetId m_assetId; // this is in case you look up by a legacy Id or other remapping and it resolves to a new ID.
AZ::Data::AssetType m_assetType = s_invalidAssetType;
AZ::u64 m_sizeBytes = 0;
};
The path already comes in from the "outPrefabAssetPath = product->GetRelativePath();" call, so I am not sure what AssetInfo will help here.

2021-09-29 15:26 UTC, AMZN-stankowi approved these changes

2021-09-29 15:26 UTC, AMZN-stankowi commented on Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
> +#include <AzToolsFramework/Prefab/Procedural/ProceduralPrefabAsset.h>
there's the same include twice here

2021-09-29 16:34 UTC, jackalbe commented on Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
> +#include <AzToolsFramework/Prefab/Procedural/ProceduralPrefabAsset.h>
dang it... will fix

2021-09-29 18:16 UTC, amzn-mike commented on Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
>              return asset.BlockUntilLoadComplete() != AZ::Data::AssetData::AssetStatus::Error;
Can you add a comment explaining that its OK for the asset to unload here because the data will get registered with the prefab system?

2021-09-29 18:16 UTC, amzn-mike approved these changes

2021-09-29 18:35 UTC, srikappa-amzn approved these changes

2021-09-29 18:35 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
> +#include <AzToolsFramework/Prefab/PrefabSystemComponentInterface.h>
Not needed anymore I think.

2021-09-29 18:35 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
> +#include <AzToolsFramework/Prefab/PrefabUndoHelpers.h>
Not needed anymore I think.

2021-09-29 18:35 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
> +                    }
Currently, every entity will be a child of a prefab instance. Entities in the level are children of level prefab instance. So this will never fail and can be removed.

2021-09-29 19:22 UTC, merged

2021-09-29 23:06 UTC, AMZN-koppersr commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            }
This does allow mixing source and product paths. It would be much safer to explicitly keep those those code path separate. An option could be to add an additional argument to indicate whether the full path is begin retrieved for a source file, a product file or that both are allowed. That would prevent regular prefabs from accidentally be accessed from the cache.