Terrain/jjjoness/phyx heightfield collider component #6422
aws-lumberyard-dev/o3de pull request #245
Opened 2021-09-29 10:12 UTC by jjjoness

Provides the PhysX Heightfield Collider.

2021-09-29 15:15 UTC, mbalfour-amzn requested changes

2021-09-29 15:15 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/BaseColliderComponent.cpp
> +        Physics::HeightfieldProviderNotificationBus::Handler::BusConnect(GetEntityId());
for the entire file:  The connections to HeightfieldProvider shouldn't be implemented in BaseCollider, this should be on the Heightfield Collider.

2021-09-29 15:15 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/EditorColliderComponent.cpp
> +                ->Field("Heightfield", &EditorProxyShapeConfig::m_heightfield)
for the entire file:  Heightfield shouldn't appear in the PhysX Collider, we have a separate PhysX Heightfield Collider for this.

2021-09-29 15:15 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/EditorForceRegionComponent.cpp
> +                }
This doesn't look right.  We have a ticket to verify and implement whatever code makes sense with the force region, which I'm pretty sure is to prevent it from being used with a heightfield, since a heightfield isn't a volume, it's a surface.  This should probably at least be an AZ_ERROR until we verify what the right behavior should be.

2021-09-29 15:15 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +                            AZ::Edit::Attributes::HelpPageURL, "https://o3de.org/docs/user-guide/components/reference/physx/shape-collider/")
This isn't the correct help page URL.

2021-09-29 15:15 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +        required.push_back(AZ_CRC("AxisAlignedBoxShapeService", 0xe86aa5fe));
All of these should be switched to use AZ_CRC_CE

2021-09-29 15:15 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +        incompatible.push_back(AZ_CRC("PhysXHeightfieldColliderService", 0x98a7e779));
Same here - AZ_CRC_CE.  You can also probably leave off LegacyCryPhysicsService, since we don't have any Cry Physics code in the codebase.

2021-09-29 15:15 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +        m_geometryCache.m_cachedSamplePointsDirty = true;
I think everything related to geometryCache can/should get removed from here - this isn't a volume, it's a surface.

2021-09-29 15:15 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
> +    };
This should be removed

2021-09-29 15:22 UTC, jjjoness commented on AutomatedTesting/Gem/Code/enabled_gems.cmake
> +    Terrain
Sorry, forgot to revert before pushing. Fixed.

2021-09-29 15:26 UTC, jjjoness commented on Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.cpp
> +    }
Done.

2021-09-29 17:05 UTC, jjjoness commented on Gems/PhysX/Code/Editor/DebugDraw.cpp
> +        }
Thanks.

2021-09-29 17:05 UTC, jjjoness commented on Gems/PhysX/Code/Source/BaseColliderComponent.cpp
> +        Physics::HeightfieldProviderNotificationBus::Handler::BusConnect(GetEntityId());
Removed from file.

2021-09-29 17:06 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorColliderComponent.cpp
> +                ->Field("Heightfield", &EditorProxyShapeConfig::m_heightfield)
Removed.

2021-09-29 17:07 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorForceRegionComponent.cpp
> +                }
Removed as no longer valid.

2021-09-29 17:08 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +                            AZ::Edit::Attributes::HelpPageURL, "https://o3de.org/docs/user-guide/components/reference/physx/shape-collider/")
Changed ready for new doc.

2021-09-29 17:09 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +        required.push_back(AZ_CRC("AxisAlignedBoxShapeService", 0xe86aa5fe));
Done.

2021-09-29 17:10 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +        incompatible.push_back(AZ_CRC("PhysXHeightfieldColliderService", 0x98a7e779));
Done.

2021-09-29 17:11 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +        m_geometryCache.m_cachedSamplePointsDirty = true;
Done.

2021-09-29 17:12 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
> +    };
Done.

2021-09-30 20:02 UTC, mbalfour-amzn requested changes

2021-09-30 20:02 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +        PhysX::ColliderShapeRequestBus::Handler::BusConnect(GetEntityId());
I'm not positive, but I think both EditorHeightfieldColliderComponent and HeightfieldColliderComponent would need to listen to the Heightfield Provider Bus.  It's possible only HeightfieldColliderComponent needs it, I'm not quite sure how the physics components work in-game vs in-editor.

2021-09-30 20:02 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
> +        AZStd::vector<AZStd::shared_ptr<Physics::HeightfieldShapeConfiguration>>m_shapeConfigs; //!< Stores the physics shape configuration(s).
When would this ever have more than one?

2021-10-03 09:36 UTC, jjjoness commented on Gems/PhysX/Code/Source/BaseColliderComponent.cpp
> +#include <AzFramework/Physics/HeightfieldProviderBus.h>
Done.

2021-10-03 09:36 UTC, jjjoness commented on Gems/PhysX/Code/Source/BaseColliderComponent.cpp
> +    }
Done

2021-10-03 09:37 UTC, jjjoness commented on Gems/PhysX/Code/Source/BaseColliderComponent.h
> +        , protected Physics::HeightfieldProviderNotificationBus::Handler
Done

2021-10-03 09:37 UTC, jjjoness commented on Gems/PhysX/Code/Source/BaseColliderComponent.h
> +
Removed.

2021-10-03 09:38 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +        incompatible.push_back(AZ_CRC_CE("LegacyCryPhysicsService"));
Done.

2021-10-03 09:38 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +        void EditorHeightfieldColliderComponent::EnablePhysics()
Done.

2021-10-03 09:39 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
> +        PhysX::ColliderShapeRequestBus::Handler::BusConnect(GetEntityId());
Will do.

2021-10-04 10:54 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
> +        AZStd::vector<AZStd::shared_ptr<Physics::HeightfieldShapeConfiguration>>m_shapeConfigs; //!< Stores the physics shape configuration(s).
Done

2021-10-04 15:00 UTC, mbalfour-amzn commented on Gems/PhysX/Code/Source/HeightfieldColliderComponent.h
> +        , protected Physics::HeightfieldProviderNotificationBus::Handler
What is this bus getting used for?  It doesn't seem like it's overriding any of the notification functions.

2021-10-04 15:07 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
> +//        Physics::HeightfieldShapeConfiguration m_shapeConfig; //!< Stores the physics shape configuration.
Was testing a change and missed this. Done now.

2021-10-04 15:07 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
> +        , protected Physics::HeightfieldProviderNotificationBus::Handler
Removed, only needed in the HeightfieldColliderComponent.

2021-10-05 16:59 UTC, jjjoness commented on Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
> +        , protected Physics::HeightfieldProviderNotificationBus::Handler
Connected now.

2021-10-05 17:00 UTC, jjjoness commented on Gems/PhysX/Code/Source/HeightfieldColliderComponent.h
> +        , protected Physics::HeightfieldProviderNotificationBus::Handler
Removed

2021-10-06 15:25 UTC, closed without merging