Migrate string generic functions
aws-lumberyard-dev/o3de pull request #307
Opened 2022-03-24 22:27 UTC by onecent1101

## Details
Move deprecated string nodes into deprecated folder
Migrate string generic function to use function autogen

## Testing
Old graph
![oldstring](https://user-images.githubusercontent.com/5900509/160020162-4ea4859b-4d99-4b8e-a1b0-1f3ba9718038.PNG)

Version converted (Ignore node which requires translation system to have pretty name)
![newstring](https://user-images.githubusercontent.com/5900509/160020222-58b8a6ea-43aa-42c1-a28e-16a1ef2e3cd9.PNG)

Signed-off-by: onecent1101 <liug@amazon.com>

2022-03-24 23:26 UTC, carlitosan requested changes
Looks good so far. I think we just need to combine the two parts of the effort.

2022-03-24 23:26 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/String/Deprecated/StringGenerics.h
> +        SCRIPT_CANVAS_GENERIC_FUNCTION_NODE_TRAIT(ToLower, ScriptCanvas::NoDefaultArguments, k_categoryName, "{FC5FA07E-C65D-470A-BEFA-714EF8103866}", true, "Makes all the characters in the string lo
Can these two be combined? I think the new macro should define what is required enough of the old node to deserialize it, AND define its replacement.

2022-03-24 23:26 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/String/Deprecated/StringGenerics.h
> +        SCRIPT_CANVAS_GENERIC_FUNCTION_NODE_TRAIT(ToUpper, ScriptCanvas::NoDefaultArguments, k_categoryName, "{323951D4-9BB1-47C9-BD2C-2DD2B750217F}", true, "Makes all the characters in the string up
We definitely need to combine these MACROS, or eliminate one. There should be no use of the traits class in the replacement macro (otherwise, it still bloats the compile times and sizes).  SCRIPT_CANVAS_GENERIC_FUNCTION_REPLACEMENT_CONFIG should the old function name, "ToLower", the old UUID, and that should be it. It should create an empty node that derives from Node, only to reflect and supply the new UUID. The registrar code may also need a replacement, to call reflect on all those nodes. They only get reflected to the serialize context. When any graph is loaded in the editor or updater, the old slot names and types will be trusted to match against the replacements specified in the code gen. Then you can delete even all of the old function definitions themselves, instead of having to leave them to drive the template instantiation.
```suggestion
        SCRIPT_CANVAS_GENERIC_FUNCTION_NODE_TRAIT(ToUpper, ScriptCanvas::NoDefaultArguments, k_categoryName, "{323951D4-9BB1-47C9-BD2C-2DD2B750217F}", true, "Makes all the characters in the string upper case", "Source");
```

2022-03-24 23:35 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/String/Deprecated/StringGenerics.h
> +        SCRIPT_CANVAS_GENERIC_FUNCTION_NODE_TRAIT(ToLower, ScriptCanvas::NoDefaultArguments, k_categoryName, "{FC5FA07E-C65D-470A-BEFA-714EF8103866}", true, "Makes all the characters in the string lo
save this advice for your next PR

2022-03-24 23:35 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/String/Deprecated/StringGenerics.h
> +        SCRIPT_CANVAS_GENERIC_FUNCTION_NODE_TRAIT(ToUpper, ScriptCanvas::NoDefaultArguments, k_categoryName, "{323951D4-9BB1-47C9-BD2C-2DD2B750217F}", true, "Makes all the characters in the string up
save this advice for your next PR

2022-03-24 23:35 UTC, carlitosan approved these changes

2022-03-25 00:31 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/String/StringFunctions.cpp
> +        AZStd::string Substring(AZStd::string sourceString, AZ::u32 index, AZ::u32 length)
IN this case, the function should accept a string_view since the sourceString isn't being modified in place.

2022-03-25 00:33 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/String/StringFunctions.cpp
> +            length = AZ::GetClamp<AZ::u32>(length, 0, aznumeric_cast<AZ::u32>(sourceString.size()));
Actually AZ::GetMin should be used since the `length` variable can never be negative.

2022-03-25 00:33 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/NodeFunctionGeneric.h
> +            replacementNode.m_type = AZ::Uuid("E42861BD-1956-45AE-8DD7-CCFC1E3E5ACF");
Can you add a comment for what this Uuid ID is for?

2022-03-26 19:26 UTC, lumberyard-employee-dm approved these changes

2022-03-28 17:13 UTC, onecent1101 commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/NodeFunctionGeneric.h
> +            replacementNode.m_type = AZ::Uuid("E42861BD-1956-45AE-8DD7-CCFC1E3E5ACF");
done

2022-03-28 17:13 UTC, onecent1101 commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/String/StringFunctions.cpp
> +        AZStd::string Substring(AZStd::string sourceString, AZ::u32 index, AZ::u32 length)
this code is copied from old generic function to keep the same as before.

2022-03-28 17:13 UTC, onecent1101 commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/String/StringFunctions.cpp
> +            length = AZ::GetClamp<AZ::u32>(length, 0, aznumeric_cast<AZ::u32>(sourceString.size()));
yep, you are correct we could use get min here, this code is copied from old generic function to keep the same as before.

2022-03-29 01:24 UTC, merged