[WIP] Add autogen registry support for nodeable
aws-lumberyard-dev/o3de pull request #375
Opened 2022-05-26 18:44 UTC by onecent1101

pending on autogen function merge

Signed-off-by: onecent1101 <liug@amazon.com>

2022-06-01 22:54 UTC, onecent1101 commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.h
> +        void UnregisterNodeable(const char* registryName);
done

2022-06-02 20:17 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.h
> +    class IScriptCanvasRegistry
No need for prefix "I"

2022-06-02 20:17 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasFunctionRegistry_Source.jinja
> +        ScriptCanvas::AutoGenRegistry::GetInstance()->RegisterRegistry(GetRegistryName(), this);
If you want to get fussy, it looks like the proper name here for the AutoGenRegistry is the `AutoGenRegistrar`

2022-06-02 20:17 UTC, lsemp3d commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.cpp
> +    AZStd::vector<std::string> AutoGenRegistry::GetRegistryNames(const char* registryName)
You should be able to use an AZStd::string rather than std::string

2022-06-02 20:17 UTC, lsemp3d commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.cpp
> +                if (registryIter != registry->m_registries.end())
I believe you can now use 
```
if (registry->m_registries.contains(name))
{ ... }
```

2022-06-02 20:17 UTC, lsemp3d commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.cpp
> +        if (m_registries.find(registryName) != m_registries.end())
```suggestion
        if (m_registries.contains(registryName))
```

2022-06-02 20:18 UTC, carlitosan approved these changes

2022-06-02 20:52 UTC, carlitosan requested changes

2022-06-02 20:52 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/ScriptCanvasCustomLibrary.h
> +#pragma once
These files should be named something other than "Custom"

2022-06-02 21:17 UTC, onecent1101 commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/ScriptCanvasCustomLibrary.h
> +            : public LibraryDefinition
done, LibraryDefinition can be removed after fully migration.

2022-06-02 21:17 UTC, onecent1101 commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/ScriptCanvasCustomLibrary.h
> +#pragma once
Renamed the file

2022-06-02 22:32 UTC, lsemp3d approved these changes

2022-06-02 23:02 UTC, carlitosan approved these changes

2022-06-03 00:01 UTC, merged