Jjjoness/rename files and folders in asset browser 1708
aws-lumberyard-dev/o3de pull request #381
Opened 2022-06-01 14:58 UTC by jjjoness

Adds the ability to rename files in the Asset Browser.

2022-06-01 15:41 UTC, cgalvan requested changes

2022-06-01 16:02 UTC, lsemp3d commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
> +                emit dataChanged(index, index);
Is it preferable to use Q_EMIT over emit?

2022-06-01 16:10 UTC, lsemp3d commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
> +                failed
These should be capitalized per coding style guidelines

2022-06-01 16:14 UTC, amzn-tmryan commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
> +                QString editName = item->GetDisplayName();
nit: Having variables named editName and editName2 doesn't tell much about what they do. They could be named something like displayFileName and baseFileName. Nitpick because the block is small, so it's easy to look it up.

2022-06-01 21:59 UTC, alexmontAmazon commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
> +                emit dataChanged(index, index);
Qt style guidelines prefer emit to Q_EMIT (Q_EMIT actually came from mobile, back in the day), but Tom's right in that it's an empty macro. I don't always type emit at all anymore

2022-06-01 22:02 UTC, alexmontAmazon commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
> +                QString editName = item->GetDisplayName();
+1

2022-06-01 22:02 UTC, alexmontAmazon commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
> +            m_name = name;
do we need to keep both m_name and m_displayName if they're effectively the same?

2022-06-06 08:54 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
> +        }
Moved the emit dataChanged into the callback and removed the blocker all together.

2022-06-06 09:05 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
> +                emit dataChanged(index, index);
I'll leave it as it is.

2022-06-06 09:05 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
> +                failed
Removed as no longer needed.

2022-06-06 09:08 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
> +                QString editName = item->GetDisplayName();
Agreed and changed.

2022-06-06 09:16 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
> +            m_name = name;
No, removed m_displayName.

2022-06-06 09:20 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
> +            m_name = name;
Actually, there is a difference as RootAssetBrowserEntry appends an [External} to the m_displayName.

2022-06-06 23:23 UTC, amzn-tmryan commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
> +            m_relativePath.ReplaceExtension(filename);
Should this line replace the extension or is filename correct?

2022-06-06 23:23 UTC, amzn-tmryan commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
> +            m_relativePath.ReplaceExtension(filename);
Should this line replace the extension or is filename correct?

2022-06-07 09:08 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
> +            m_relativePath.ReplaceExtension(filename);
Good spot. Changed the code.

2022-06-07 09:08 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
> +            m_relativePath.ReplaceExtension(filename);
As above.

2022-06-07 18:18 UTC, amzn-tmryan approved these changes

2022-07-06 15:28 UTC, cgalvan requested changes

2022-07-06 15:28 UTC, cgalvan commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.h
> +            int LeftmostColumn(void);
Remove `void` type with no param in signature

2022-07-06 15:28 UTC, cgalvan commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp
> +            int retval{ 0 };
Should this be `-1` by default since with this logic if `filterAcceptsColumn` fails for each column supplied it will still return `0` even if that column index failed `filterAcceptsColumn` ?

2022-07-06 15:28 UTC, cgalvan commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
> +#include <QApplication>
Please keep alphabetical ordering of includes intact here. Also, it appears `QThread` and `QApplication` are unused, can they be removed?

2022-07-06 15:28 UTC, cgalvan commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
> +
Remove extra whitespace added here

2022-07-06 15:29 UTC, cgalvan commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
> +        }
Awesome, thanks!

2022-07-06 15:37 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.h
> +            int LeftmostColumn(void);
Ooops. Done.

2022-07-06 15:37 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp
> +            int retval{ 0 };
Done.

2022-07-06 15:37 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
> +#include <QApplication>
All done.

2022-07-06 15:38 UTC, jjjoness commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
> +
done.

2022-07-06 15:43 UTC, cgalvan approved these changes

2022-07-06 15:44 UTC, merged