Simple Hot Reload Prototype
aws-lumberyard-dev/o3de pull request #383
Opened 2022-06-02 00:18 UTC by EnochAmeyaw

Added reload function for simple hot reloading and added setting registry flag.

2022-06-03 21:50 UTC, AMZN-daimini approved these changes
Nice to see this! I have a few questions and quite a few nitpicks (sorry about that :D ).

Also, question: will follow-up PRs handle the case where we have unsaved changes to the template in-memory, and the file is changed on disk? Cause with the current logic, changes to the file in memory are going to just stomp the local changes in memory with no user confirmation... so the UX could be improved :D

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabEditorPreferences.h
> +} // namespace AzToolsFramework
Since this check is Prefab specific, it should likely either be under the AzToolsFramework::Prefab namespace, or include Prefab in the name.

So either
```
namespace AzToolsFramework::prefab
```

or

```
bool IsPrefabHotReloadEnabled();
```

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +
nit: remove double newline

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +
nit: remove extra newlines

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +
nit: remove extra newline

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            //isLoadSuccessful &= SanitizeLoadedTemplate(prefabDom);
Remove commented out code. If you want to mark this spot for future additions, prefer a "TODO" style comment (but remember to remove them when merging to development)

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +           // Directly return loaded Template id.
nit: wrong indentation (missing one space?)

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.h
> +             * @return A unique id of Template on filePath loaded. Return invalid template id if loading Template on filePath failed.
Function is void, so the return part of the comment is incorrect

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +        {
I'm thinking if this is the correct API - would it make more sense for this function to accept the TemplateId instead? It should be possible to retrieve the filePath from the TemplateId then.

Not really a blocker, mostly just me thinking out loud :)

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +
nit: remove extra newline

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +                m_prefabLoader.ReloadTemplateFromFile(relativePath.c_str());
Should this be an error? It sounds like it's exactly what this function is for :D

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +            return;
nit: unnecessary return.

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +        void PrefabSystemComponent::SourceFileRemoved(
nit: add a newline between functions

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.h
> +            //! Called by the AssetProcessor when a source of an asset has been removed.
nit: removed -> changed

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.h
> +            //! Called by the AssetProcessor when a source of an asset has been removed.
every product asset has a single source, so I think "a source" should be changed to "the source"?

2022-06-03 21:50 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabEditorPreferences.cpp
> +        // Retrieve new setting
nit: comment isn't very helpful :)

2022-06-03 22:00 UTC, srikappa-amzn requested changes

2022-06-03 22:00 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.h
> +            //! Called by the AssetProcessor when a source of an asset has been removed.
I'd like to avoid the usage of asset altogether since prefabs are not loaded as Asset<T> . I recommend 'when a source file has been removed' instead

2022-06-03 22:21 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +                m_prefabLoader.ReloadTemplateFromFile(relativePath.c_str());
Error should be removed

2022-06-03 22:21 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +            AZ_Error("Prefab", false, "File removed", relativePath.c_str());
Add a //TODO comment here and remove the AZ_Error  since this is not a valid error as well.

2022-06-03 22:21 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.h
> +             * into fully formed nested template info.
nit: this part can be removed since its the same as loading a prefab from file

2022-06-03 22:21 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +        {
We can possibly add a ReloadTemplate(TemplateId) function in the future if needed. Given that we already get the file to begin with, fetching the template id and fetching the file again will be cyclical and unnecessary.

2022-06-03 22:21 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            }
Line 80 till here can be put in a static helper function called ReadPrefabFile() and shared by Load and Reload() functions.

2022-06-03 22:21 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +        void PrefabLoader::ReloadTemplateFromFile(AZ::IO::PathView filePath)
nit: rename this to 'relativeFilePath' to indicate that this should be relativeFilePath

2022-06-03 22:21 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            //progressedFilePathsSet.emplace(filePath);
This can be uncommented. So the flow is:
1. Add the filePath to ProgressedFilePathsSet
2. Load nested prefabs
3. Remove the filePath from ProgressedFilePathsSet

2022-06-03 22:27 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +        {
Yeah I'm mostly thinking in the context of possibly adding a "Reload prefab from disk" menu option for prefabs in the scene.
The code that calls this function now already has to check if the prefab is loaded in memory either way, so getting the template id is not very expensive.

2022-06-08 21:37 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabEditorPreferences.cpp
> +namespace AzToolsFramework::prefab
The correct namespace is Prefab (capitalized)

2022-06-08 21:37 UTC, AMZN-daimini commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabEditorPreferences.h
>  } // namespace AzToolsFramework
Should have the same namespace as the cpp file (I'm not sure if this builds?)

2022-06-09 05:38 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabEditorPreferences.cpp
> +} //namespace AzToolsFramework::prefab
fix capitalization here as well.

2022-06-09 05:38 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +        TemplateId PrefabLoader::ReadPrefabFile(AZ::IO::PathView relativePath, AZStd::unordered_set<AZ::IO::Path> progressedFilePathsSet)
Seems like nothing else is using this newly added function. Remove this if not needed.

2022-06-09 05:38 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.h
> -             */
I think you may have misunderstood my previous comment. These function comments are infact useful. I only suggested that lines 59 and 60 are removed because that is duplicate info. Also remove the @return comment since this function doesn't return anything.

2022-06-09 21:45 UTC, merged