Prefab hot reloading/remove
aws-lumberyard-dev/o3de pull request #401
Opened 2022-06-20 23:18 UTC by EnochAmeyaw

2022-06-20 23:38 UTC, srikappa-amzn requested changes

2022-06-20 23:38 UTC, srikappa-amzn commented on Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
> +
remove all empty lines in this file. This file shouldn't show up in the PR

2022-06-20 23:38 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +#pragma optimize("", on)
Remove.

2022-06-20 23:38 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +
Remove. This will remove all optimizations on the class if pushed to development

2022-06-20 23:38 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                AZ::Failure(AZStd::string("Could not focus on root prefab instance - internal error "
Comment needs to be changed. Also, this needs to be an AZ_Assert()

2022-06-21 00:14 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +
This should be removed since you are erasing the same path few lines below.

2022-06-21 00:14 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +
nit: remove empty line

2022-06-21 00:14 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +        void PrefabLoader::RemoveTemplateFromEditor()
Upon further thought, all this function does is ask that the root prefab instance be updated from its template. I recommend that the logic be moved into a static helper function in PrefabSystemComponent.cpp . 

Also, instead of calling PropagateTemplateChanges(), you can just call UpdatePrefabInstances()

2022-06-21 22:10 UTC, srikappa-amzn approved these changes

2022-06-21 22:10 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +                AZ_Assert(prefabEditorEntityOwnershipInterface, "PrefabEditorEntityOwnershipInterface unavailable");
I believe it's technically possible to create a prefabsytemcomponent without an editor in some cases. So, remove this assert and wrap the logic below inside an if check: 
```
if (prefabEditorEntityOwnershipInterface != nullptr)
{
}
```

2022-06-21 23:17 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +               m_prefabLoader.ReloadTemplateFromFile(relativePath.c_str());
nit: missing a space. Line 192 has an extra space.

2022-06-22 05:43 UTC, forkercat approved these changes

2022-07-07 19:36 UTC, merged