Add more nodes to the palette and more options for their data
aws-lumberyard-dev/o3de pull request #402
Opened 2022-06-21 17:54 UTC by mddvisu

Added more small operator nodes to the palette and allowed the user to enter the type of data that the node accepts and the tooltip of the node. Did some cleaning as well.

<img width="823" alt="moresmalloperators" src="https://user-images.githubusercontent.com/105814224/174866155-80e7cece-0d0d-46b7-8bbc-a8dcd812e931.png">

2022-06-21 18:39 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
> +            "Increment");
Can we hold that for a PR? His next step may to be to populate these entire sets of nodes by reading in file data.

2022-06-21 18:47 UTC, carlitosan requested changes

2022-06-21 18:47 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
> +        if (node->GetNodeToolTip() == "")   // Old way of setting the node tooltip
What does this return? If any class based string type, use `.empty()` instead of `== ""`

2022-06-21 18:47 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
> +                ->Field("NodeId", &CreateDataDrivenNodeMimeEvent::m_nodeId)
`NodeTypeId` a `NodeID` sounds like the id of the node in the graph...or something else. This name and others related to it, like the member variable need a little more clarity.

2022-06-21 18:47 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
> +        nodePaletteModel.RegisterSmallOperatorNode(
This is pretty great. And, as you can now see, a very good candidate to drive all of this from data from disk.

2022-06-21 19:06 UTC, mddvisu commented on Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
> +        if (node->GetNodeToolTip() == "")   // Old way of setting the node tooltip
I added a tooltip attribute to the Node class so that data driven nodes can store their tooltips. This is just its getter.

2022-06-21 19:15 UTC, mddvisu commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
> +                ->Field("NodeId", &CreateDataDrivenNodeMimeEvent::m_nodeId)
How about NodeDefaultsId?

2022-06-21 19:34 UTC, onecent1101 commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.h
> +            const AZStd::string& palettePath = "Math/Small Operators");
Minor: when there are such many parameters need to pass in, you can consider create data structure to hold it and pass the data structure instead? (which is much more flexible for future update instead of changing function signature frequently)

2022-06-21 22:28 UTC, carlitosan requested changes

2022-06-21 22:28 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
> +        return Nodes::CreateDataDrivenNode(m_userData, m_nodeDefaultsId, scriptCanvasId);
rename m_nodeDefaultsId --> m_nodeTypeId or m_nodeLexicalId

2022-06-21 22:28 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.cpp
> +    AZStd::string Node::GetNodeToolTip() const
return type should be `const AZStd::string&` especially since the function is marked const.

2022-06-21 23:08 UTC, mddvisu commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.h
>          virtual AZStd::string GetNodeTypeName() const;
Changing GetNodeTypeName to return a constant reference breaks a multitude of other things

2022-06-21 23:55 UTC, lsemp3d commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
> +            "Increment");
Yea, that can definitely be its own PR

2022-06-22 17:53 UTC, onecent1101 approved these changes

2022-06-22 17:53 UTC, onecent1101 commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
> +                ->Field("nodeLexicalId", &CreateDataDrivenNodeMimeEvent::m_nodeLexicalId)
Minor: camel case?

2022-06-22 17:53 UTC, onecent1101 commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
>                  ->Field("NodeData", &CreateDataDrivenNodeMimeEvent::m_userData);
Minor: UserData?

2022-06-23 00:04 UTC, merged