reload nested prefabs to update specific patches
aws-lumberyard-dev/o3de pull request #406
Opened 2022-07-07 20:13 UTC by EnochAmeyaw

Signed-off-by: Enoch Ameyaw <eameyaw@amazon.com>

2022-07-08 17:57 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            //Retrieving dom from the loaded template
nit: missing space after //

2022-07-08 17:58 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            //Retrieving dom from the loaded template
Can this be encapsulated in a function?

2022-07-08 17:59 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +               const PrefabDomValue& instances = instancesReference->get();
nit: indent issue

2022-07-08 18:08 UTC, srikappa-amzn requested changes
Nice job modularizing the code with a helper function!

2022-07-08 18:08 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                    AZStd::string_view nestedTemplatePath(newSource.GetString(), newSource.GetStringLength());
What if both the source and the patches change on file?

In addition to modifying the source templateId, this block also need to fetch the patches and update target. So, I suggest you change this to:

```
if(nestedTemplateSource->get() != sourceOnFile->get())
{
    const PrefabDomValue& newSource = sourceOnFile->get();
    AZStd::string_view nestedTemplatePath(newSource.GetString(), newSource.GetStringLength());
    TemplateId newSourceTemplateId = LoadTemplateFromFile(nestedTemplatePath, progressedFilePathsSet);
    targetLink.SetSourceTemplateId(newSourceTemplateId);
}
targetLink.SetLinkDom(fileDom);
targetLink.UpdateTarget();
return true;
```

2022-07-11 20:19 UTC, AMZN-mnaumov commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                //TODO: Add a new link
might want to include GH issue in the comment or remove else altogether

2022-07-11 20:19 UTC, AMZN-mnaumov approved these changes

2022-07-11 21:37 UTC, srikappa-amzn approved these changes

2022-07-11 21:37 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                AZ_Error(
repeated: Add an empty return after throwing these errors in this function. Otherwise, the code will probably crash at a later point when trying to access something that didn't exist.

2022-07-18 20:20 UTC, merged