Lyn 10531/pass system
aws-lumberyard-dev/o3de pull request #421
Opened 2022-07-19 07:48 UTC by jonawals

## What does this PR do?

_Please describe your PR. For a bug fix, what was the old behavior, what is the new behavior?_

_Please add links to any issues, RFCs or other items that are relevant to this PR._

## How was this PR tested?

_Please describe any testing performed._

2022-07-19 19:27 UTC, rainbj commented
Hi @hultonha and @jonawals. During our UX review, this ticket came up as a point of interest and wanting to talk about selecting a hierarchy of object. Meaning, anything that is directly owned by the object could have two different color lines (direct ownership -yellow and child ownership -white). Just an idea we should do some exploration on and this is not a hard requirement. Apparently this seems to be a pattern that other game engines have utilized and might be something we want to consider.  I've grabbed your video above and made an example image based on this idea. Two different examples.
![ideas](https://user-images.githubusercontent.com/82551958/179831832-44bc40fb-3d6d-4b1a-8372-c935da276a2a.png)

CC'ing @AMZN-daimini and @amzn-leenguy

2022-07-20 14:06 UTC, hultonha commented
> Hi @hultonha and @jonawals. During our UX review, this ticket came up as a point of interest and wanting to talk about selecting a hierarchy of object. Meaning, anything that is directly owned by the object could have two different color lines (direct ownership -yellow and child ownership -white). Just an idea we should do some exploration on and this is not a hard requirement. Apparently this seems to be a pattern that other game engines have utilized and might be something we want to consider. I've grabbed your video above and made an example image based on this idea. Two different examples. ![ideas](https://user-images.githubusercontent.com/82551958/179831832-44bc40fb-3d6d-4b1a-8372-c935da276a2a.png)
> 
> CC'ing @AMZN-daimini , @amzn-leenguy , and @yuyihsu

That's an interesting idea @rainbj, this is definitely something we can look into for a future update. @jonawals can probably give an indication as to how much work this may or may not be. It might be worth creating a ticket to track this explicitly (ping me offline and I can make one we can track more easily). This work will likely need to be deferred until a bit later in the year though, but I do think it's a great suggestion. Thanks!

2022-07-20 17:11 UTC, hultonha approved these changes
Overall looks like a great change, really awesome work @jonawals. The majority of my comments are nits with a couple of other questions/suggestions sprinkled in. 

Would also be great to have some performance captures of this change when the editor is running too in the PR description to show we've done our due diligence on this.

Really fantastic to see! 🙂

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.cpp
> +        const AZStd::string& maskDrawList)
suggestion: As we pass these to `AZStd::string` and `AZ::Name` (that both have a `string_view` constructor) consider passing these as `string_view`s so you don't have to construct a string when passing a string literal to the constructor.

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.cpp
> +        const AZStd::string& maskDrawList)
(repeated below)

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.cpp
> +        return Name(GetStateName() + "Template");
suggestion: Could use `AZStd::string::format` here - should be quite a bit faster

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.h
> +        //! Returns the name of the entity mask daw list used this editor state.
nit: daw -> draw

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.h
> +        ChildPass* FindChildPass(RPI::ParentPass* parentPass, std::size_t index) const
update: Remove `std::` prefix here and just use `size_t`

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.h
> +        EditorState m_state; //!<  The editor state enumeration this editor state effect pass is associated with.
uber nit: extra space after //!< 😅

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityParentPass.cpp
> +    }
question: In future would it be possible to allow the user to tweak this when the effect is created to enable/disable certain kinds of effects?

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityParentPass.cpp
> +        }
update: Might this potentially be safer as `m_inFocusMode = mode == AzToolsFramework::ViewportEditorMode::Focus`? (same below)

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityParentPass.cpp
> +}
uber nit: Missing closing namespace (again clang-format should fix this)

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/SelectedEntityParentPass.cpp
> +    // Indicies of child passes (a better way to do this will be to specifiy a pass template name/effect name pair for the
nit: Indicies -> Indices

2022-07-20 17:11 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/SelectedEntityParentPass.cpp
> +    }
suggestion: Would be great to have a test for this function at some point, looks like it could possibly just be a free function too making it easier to test

2022-07-20 17:11 UTC, hultonha commented
Also would be good to get some sig graphics/audio eyes on this before merging too :+1:

2022-07-20 17:21 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityParentPass.cpp
> +    }
yes, although the editor state effect classes will provide a simpler abstraction of these individual child passes (see the `SelectedEntityParentPass` for something a little like this in the commented out bits).

so, for example, rather than exposing each individual parameter of each indivudual child pass, the `FocusedEntityParentPass` would instead expose a simple interface like `EffectStrength`, `BackgroundDistance`, `BackgroundColor` or whatever that is manipulated by the appropriate `FocusedEntityEffectRequestsBus` (or whatever better name) that `FocusedEntityParentPass` implements.

2022-07-21 00:42 UTC, antonmic requested changes
Quite confused about the design here. You created a system to add groups of passes in cpp, which the pass system can already do in a data driven way. This is contrary to previous feedback I gave and I'd like to have a sync meeting to discuss what exactly the goal with this design is.

2022-07-21 10:47 UTC, hultonha commented
> Quite confused about the design here. You created a system to add groups of passes in cpp, which the pass system can already do in a data driven way. This is contrary to previous feedback I gave and I'd like to have a sync meeting to discuss what exactly the goal with this design is.

2022-07-21 10:51 UTC, hultonha commented
Apologies I hit the wrong button and accidentally closed, now re-opened, please ignore. Thanks!

2022-07-25 12:47 UTC, hultonha commented
For visibility @jonawals, @antonmic, @rainbj and myself are going to have a quick call about this to discuss and will return to the PR feedback once it's concluded.

2022-07-28 10:59 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Assets/Shaders/EditorModeBufferCopy.azsl
> +}
This was discussed offline and is part of the design approach we've taken. This will not be updated as part of this PR.

2022-07-28 11:01 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPass.cpp
> +        return passData->editorStatePass->IsEnabled();
This was discussed offline. In this case `passData->editorStatePass->IsEnabled()` is not a global boolean for the EMVF system itself, rather each Editor State has its own means of communicating back to the Editor State class whether it should be enabled or disabled. For this PR we will leave this as-is.

2022-07-28 11:03 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateBufferCopyPass.cpp
> +    bool EditorStateBufferCopyPass::IsEnabled() const
This was discussed offline - plan is to leave this as-is for now (please see previous comment about `EditorStateParentPass`).

2022-07-28 11:08 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
> +        }
We've created this follow-up GHI to discuss in a few weeks time - https://github.com/o3de/o3de/issues/10933

2022-07-28 11:13 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
> +            }
This was discussed offline. There are a few reasons why this is necessary today, this is something we're aware of and will review in future. Internal issue made to track for now.

2022-07-28 11:18 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystemUtils.cpp
> +            auto childPassName = Name(AZStd::string::format("%sChildPass%u", stateParentPassTemplate->m_name.GetCStr(), passCount));
Discussed with @jonawals and this is easy to fix by just appending the pass name to this string.

2022-07-28 11:20 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystemUtils.cpp
> +            }
This was discussed offline, this is part of the design we decided to go with (for better or worse). The plan is to role with this approach and review if it is fit for purpose or not once we have had time to live with it and see how things work.

2022-07-28 11:22 UTC, hultonha commented
> Think I only marked two comments as needing resolution before this PR gets submitted, the rest can be addressed in follow up changes. Please create github issues for the creation of multiple mask passes and multiple copy passes as this is very wasteful performance wise. Did you test these changes with multiple pipelines active? (you can do this by enabling multiple viewports in the editor)

Thanks for the feedback, reviewing with @jonawals. We will follow-up on the question:

> Did you test these changes with multiple pipelines active? (you can do this by enabling multiple viewports in the editor)

And report back (unfortunately I think this feature to enable multiple viewports was disabled recently as it did not have full UX support, @AMZN-daimini might know how to quickly turn it back on again). 

We have created a new GHI (https://github.com/o3de/o3de/issues/10933) to follow-up on the pass/mask design for a future PR and also one internal issue for our team to look at concerning pass injection.

Once immediate remaining feedback is addressed could you please remove the 'Request changes' block. Thank you for your time.

2022-07-29 20:11 UTC, antonmic approved these changes

2022-08-04 09:31 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Include/EditorModeFeedback/EditorStateRequestsBus.h
> +        static const AZ::EBusHandlerPolicy HandlerPolicy = AZ::EBusHandlerPolicy::Multiple;
Single should suffice. Fixed 👍

2022-08-04 09:31 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.cpp
> +            const AZStd::string path = "shaders/editormodemask.azmaterial";
Fixed 👍

2022-08-04 09:35 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.cpp
> +
Fixed 👍

2022-08-04 09:36 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.cpp
> +        void EditorModeFeatureProcessor::Render(const RenderPacket&)
Fixed 👍

2022-08-04 09:36 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.h
> +            void Render(const RenderPacket&) override;
Fixed 👍

2022-08-04 09:38 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
> +        passSystem->AddPassCreator(Name("EditorModeOutlinePass"), &EditorModeOutlinePass::Create);
Fixed 👍

2022-08-04 09:41 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
> +                const auto entityIds = state->GetMaskedEntities();
Good Q, but no, as this function is for prodding the instances to return a vector value of the entities that pertain to their state.

2022-08-04 09:42 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
> +        if (mainPass)
Fixed 👍

2022-08-04 09:43 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateBufferCopyPass.cpp
> +        RPI::PassUtils::GetPassData<RPI::EditorStateBufferCopyPassData>(m_passDescriptor);
Fixed 👍

2022-08-04 09:43 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateBufferCopyPass.h
> +    //! Pass class for the EditorStateBufferCopy pass.
Fixed 👍

2022-08-04 09:46 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.h
> +        //! Returns the name of the entity mask daw list used this editor state.
Fixed 👍

2022-08-04 09:49 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.h
> +        [[nodiscard]] virtual AzToolsFramework::EntityIdList GetMaskedEntities() const = 0;
Moved 👍

2022-08-04 09:49 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.h
> +        ChildPass* FindChildPass(RPI::ParentPass* parentPass, std::size_t index) const
Fixed 👍

2022-08-04 09:53 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.h
> +        EditorState m_state; //!<  The editor state enumeration this editor state effect pass is associated with.
Fixed 👍

2022-08-04 09:54 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityParentPass.cpp
> +}
Fixed 👍

2022-08-04 09:54 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/SelectedEntityParentPass.cpp
> +    // Indicies of child passes (a better way to do this will be to specifiy a pass template name/effect name pair for the
Fixed 👍

2022-08-04 09:55 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/SelectedEntityParentPass.cpp
> +    }
Indeed, I will reach out to @AMZN-daimini as he has some very similar code elsewhere.

2022-08-04 09:56 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystemUtils.cpp
> +        AZStd::unordered_set<Name> drawLists;
This will only be called once at startup so probs not worth it.

2022-08-04 09:57 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateBufferCopyPass.cpp
> +        return AZStd::move(pass);
I will check this when I merge into the staging buffer as I cannot say with 100% confidence that it won't have unintended consequences 👍

2022-08-04 09:59 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityParentPass.cpp
> +        }
Fixed 👍

2022-08-04 10:08 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Include/EditorModeFeedback/EditorStateRequestsBus.h
> +        static const AZ::EBusHandlerPolicy HandlerPolicy = AZ::EBusHandlerPolicy::Multiple;
Excellent thanks!

2022-08-04 10:09 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.cpp
> +
Thanks!

2022-08-04 10:12 UTC, hultonha commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/SelectedEntityParentPass.cpp
> +    }
Sounds great, we can totally come back to this later though :+1:

2022-08-04 10:14 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.cpp
> +        }
Fixed 👍

2022-08-04 10:16 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
> +    static constexpr const char* const MainPassParentPassName = "EditorModeFeedbackPassParent";
Fixed 👍

2022-08-04 10:27 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
> +        m_masks = CreateMaskPassTemplatesFromStateParentPasses(m_editorStateParentPasses);
I will address this issue when thus PR gets merged into the staging buffer as it will require some experimentation 👍

2022-08-04 12:17 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.h
> +        ChildPass* FindChildPass(RPI::ParentPass* parentPass, std::size_t index) const
It's used in the `SelectedEntityState` class.

2022-08-04 12:22 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.h
> +        void InitPasses(RPI::RenderPipeline* renderPipeline);
This has been renamed to `ConfigureStatePassesForPipeline` 👍

2022-08-04 12:34 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.h
> +    using PassDescriptorList = AZStd::vector<Name>;
Fixed 👍

2022-08-04 12:35 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/SelectedEntityParentPass.h
> +    class SelectedEntityParentPass
Fixed 👍

2022-08-04 12:43 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystemUtils.cpp
> +            auto childPassName = Name(AZStd::string::format("%sChildPass%u", stateParentPassTemplate->m_name.GetCStr(), passCount));
Fixed 👍

2022-08-04 12:43 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.cpp
> +    }
Fixed 👍

2022-08-04 12:44 UTC, jonawals commented on Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassBase.h
> +    class EditorStateParentPassBase
Fixed 👍

2022-08-04 13:09 UTC, merged