Prefab hot reloading/add link
aws-lumberyard-dev/o3de pull request #428
Opened 2022-07-20 20:13 UTC by EnochAmeyaw

Adding a link for the hot reload process when a new nested instance on file is not being shown on the template

2022-07-20 23:54 UTC, srikappa-amzn requested changes

2022-07-20 23:54 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            //PrefabDomPath instanceRetriever = PrefabDomUtils::GetPrefabDomInstancePath(instanceIterator->name.GetString());
remove commented line.

2022-07-20 23:54 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                PrefabDomUtils::FindPrefabDomValue(instancesRetriever->get(), instanceIterator->name.GetString());
You can use PrefabDomUtils::GetPrefabDomInstancePath() to fetch the path and just check whether it exists in the dom once instead of doing 2 individual checks.

2022-07-20 23:54 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                if (!LoadNestedInstance(instanceIterator, targetTemplateId, progressedFilePathsSet))
delete this if check. You should only either be adding a link or loading nested instance.

2022-07-20 23:54 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
> +               link.GetLinkDom().AddMember(
you should be adding an empty object to the template dom, not the link dom

2022-07-21 17:19 UTC, srikappa-amzn approved these changes
Looks good to me.

2022-07-21 19:00 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
>               existingEntitiesReference->get().CopyFrom(entitiesReference->get(), existingTemplateDom.GetAllocator());
nit: extra space

2022-07-21 19:00 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
>                  {
nit: indent is not consistent

2022-07-21 19:00 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +            PrefabDomValueReference instancesReference = PrefabDomUtils::GetInstancesValue(loadedDomFromFile);
```suggestion
            PrefabDomValueReference instancesDomReference = PrefabDomUtils::GetInstancesDomValue(loadedDomFromFile);
```
to avoid confusion

2022-07-21 19:00 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +             PrefabDomValue* instanceValue = instancePath.Get(templateDom);
nit: indent

2022-07-21 19:00 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                PrefabDomValue& newSource = sourceValueInDomFromFile->get();
Adding a comment for each branch would be great.

2022-07-21 19:00 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                 // locating the link id in the existing nested dom
nit: Locating

2022-07-21 19:00 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                PrefabDomValue& newSource = sourceValueInDomFromFile->get();
Also, I would prefer switching the branch for readability.
```cpp
if (!instanceDomValue)  // which is instanceValue in your code
{
    // Add new link
}
else
{
    // Update existing links
}
```

2022-07-21 19:00 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                 Link& targetLink = targetLinkReference->get();
nit: add more empty line

2022-07-21 23:23 UTC, forkercat commented
Looks good!

2022-07-27 17:24 UTC, merged