Initial prototype for removing link on reload
aws-lumberyard-dev/o3de pull request #437
Opened 2022-07-27 18:37 UTC by EnochAmeyaw

Signed-off-by: Enoch Ameyaw <eameyaw@amazon.com>

Propagates changes to the editor when a nested instance is removed on file

2022-07-27 19:04 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +        bool PrefabLoader::RemoveLinkOnReload(PrefabDomValue& fileInstances, PrefabDomValueReference templateInstancesReference)
function name indicates that you should always remove some link. Maybe change it something like 'RemoveStateLinksOnReload'

2022-07-27 19:04 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                if (!RemoveLinkOnReload(instances, instancesTemplateReference))
Good job modularizing the code. Something to keep in mind for future PRs is that this function already is pretty big at this point. So, we should probably break it down into even smaller chunks for better readability.

2022-07-27 19:15 UTC, forkercat reviewed
Left some suggestions

2022-07-27 19:15 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                }
suggestion: Moving the `has_value()` validation to `RemoveLinkOnReload`.

2022-07-27 19:15 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +        bool PrefabLoader::RemoveLinkOnReload(PrefabDomValue& fileInstances, PrefabDomValueReference templateInstancesReference)
suggestion (following the above comment): Can this be changed to the following?
```
RemoveLinkOnReload(
    PrefabDomValueReference templateDomReference, 
    PrefabDomValueConstReference templateDomFromFileReference
)
```

2022-07-27 23:07 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +        bool PrefabLoader::RemoveLinkOnReload(PrefabDomValue& fileInstances, PrefabDomValueReference templateInstancesReference)
@srikappa-amzn Do you mean "Stale"?

2022-07-27 23:58 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +        bool PrefabLoader::RemoveLinkOnReload(PrefabDomValue& fileInstances, PrefabDomValueReference templateInstancesReference)
yes

2022-07-28 00:01 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                    if (!RemoveStateLinksOnReload(instances, instancesTemplateReference->get()))
This shouldbe 'StaleLinks'. Sorry for the typo earlier.

2022-07-28 00:19 UTC, forkercat commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                }
Had a discussion. Looks like after L200, we need to (1) remove stale links (2) reload nested instances.

Does it provide better readability if we add a new private helper function `ReloadInstances()` (or a better name) that encapsulates `RemoveStaleLinksOnReload()` and `ReloadNestedInstances()`?

```cpp
// Reloads instances if there are instances on file.
if (instancesFileReference.has_value())
{
    ReloadInstances(/* pass needed arguments */);
}

SanitizeLoadedTemplate(existingTemplateDom);
// Un-mark the file as being in progress.
progressedFilePathsSet.erase(relativePath);
```

ReloadInstances():
```cpp
ReloadInstances()
{
    if (!instancesTemplateReference.has_value())
    {
        // error
        return false;
    }
    
    // Removes stale links
    RemoveStaleLinksOnReload();

    // Reload nested instances
    // ...
    return true;
}
```
Feel free to drop my suggestion if you don't agree. I might have missed sth :)

2022-07-28 01:11 UTC, forkercat requested changes
Thanks for reorganizing the code. It looks better!

2022-07-28 19:20 UTC, srikappa-amzn requested changes

2022-07-28 19:20 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.h
> +             * Removes links from given template instances that are no longer shown on file.
nit: 'that are not present in the dom loaded from file'

2022-07-28 19:20 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.h
> +             * @param instancesFileReference A reference to an instance file dom containing updated nested instances.
nit: 'Reference to the nested instances in the dom loaded from file'

2022-07-28 19:20 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.h
> +             * @param instancesTemplateReference A reference to an instance dom containing nested instances.
nit: 'Reference to the nested instances in the existing template dom'

2022-07-28 19:20 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                return;
Since you are throwing individual errors from within RemoveStaleLinks() function, this kind of generic error statement doesn't add much value. I suggest that you change the return value to void and remove this error message.

2022-07-28 19:20 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                return;
The job of this function is to detect if there are instance keys on template that can't be found in the file dom. So, if there are not instances on the template, it can return without an error.

If there are no instances in the file dom but there are instances on the template, then all links to be removed.
Make sure  that case is covered as well.

2022-07-28 19:20 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                return;
You can do that by changing line 253 to 
```
if (instancesFileReference.has_value() == false || instancesFileReference->get().HasMember(instanceIterator->name))

```

2022-07-29 16:38 UTC, srikappa-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
> +                if (instancesFileReference.has_value() == false || instancesFileReference->get().HasMember(instanceIterator->name))
shouldn't the second check be 
```
instancesFileReference->get().HasMember(instanceIterator->name) == false
```

2022-07-29 16:39 UTC, srikappa-amzn approved these changes
Noticed a small logical error. But looks good otherwise!

2022-07-29 17:15 UTC, forkercat approved these changes

2022-08-02 18:35 UTC, merged