Initial commit.
aws-lumberyard-dev/o3de pull request #486
Opened 2023-01-12 10:14 UTC by jonawals

Signed-off-by: John <jonawals@amazon.com>

## What does this PR do?

_Please describe your PR. For a bug fix, what was the old behavior, what is the new behavior?_

_Please add links to any issues, RFCs or other items that are relevant to this PR._

## How was this PR tested?

_Please describe any testing performed._

2023-01-12 21:08 UTC, spham-amzn commented on scripts/build/TestImpactAnalysis/test_impact/base_test_impact.py
> +
You could probably replace this with 
```suggestion
        multi_values_string = "-".join(multi_values)
```

2023-01-12 21:09 UTC, spham-amzn commented on scripts/build/TestImpactAnalysis/test_impact/base_test_impact.py
> +
You could probably replace this loop with
```suggestion
        multi_values_string = "-".join(multi_values)
```

2023-01-12 21:15 UTC, spham-amzn commented on scripts/build/TestImpactAnalysis/test_impact/base_test_impact.py
> +                    self._runtime_args.append(f"{argument.runtime_arg}{value}")
```suggestion
                self._runtime_args.append(f"{argument.runtime_arg}{','.join(value) if type(value)==list else value})
```

2023-01-12 21:17 UTC, lumberyard-employee-dm commented on scripts/build/TestImpactAnalysis/test_impact/base_test_impact.py
> +                    self._runtime_args.append(f"{argument.runtime_arg}{value}")
The `type` keyword shouldn't be used in this case as it would form an exact match, but instead the isintance keyword should be used as that is more [pythonic](https://stackoverflow.com/questions/1549801/what-are-the-differences-between-type-and-isinstance).
```suggestion
                self._runtime_args.append(f"{argument.runtime_arg}{value if isinstance(value, str) else ','.join(value)}") 
```

2023-01-12 21:17 UTC, lumberyard-employee-dm commented on scripts/build/TestImpactAnalysis/test_impact/base_test_impact.py
> +                    self._runtime_args.append(f"{argument.runtime_arg}{value}")
Same comment too bro!

2023-01-12 21:19 UTC, lumberyard-employee-dm commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage_s3.py
> +        @param suites_string: The concatenated test suites string for which the historic data will be obtained for.
How is this concatenated? Is it with commas? spaces?

That is something important to mention in the PyDoc. so that users know how to concatenate the strings to together.

2023-01-12 21:25 UTC, spham-amzn commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage_local.py
> +                logger.error(f"Error copying tree '{source_directory}' to '{target_directory}'")
nit: Since this is being updated anyways, can you report the exception/error on the same logger.error instead of doing it in a separate error logger call? (and remove the separate logger below this line)

2023-01-12 21:26 UTC, lumberyard-employee-dm commented on scripts/build/TestImpactAnalysis/test_impact/runtime_test_impact_args.py
> +    COMMON_LABEL_EXCLUDES = ("label_excludes", "--labelexcludes=", "Suite label excludes is set to: ")
For CLI tool arguments the eco system uses dashes(`-`) instead of underscores('_') for arguments.
For example the [GNU style guide](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) mentions to separate long options using hyphens

i.e
![image](https://user-images.githubusercontent.com/56135373/212183935-e409c367-c2fa-4b56-a2b6-16772a244f82.png)

2023-01-12 21:28 UTC, lumberyard-employee-dm commented on scripts/build/TestImpactAnalysis/tiaf_driver.py
> +        required=False
This should use `nargs='*'` since this is not a [required](https://docs.python.org/3/library/argparse.html#nargs) argument.

2023-01-12 22:38 UTC, evanchia-ly-sdets requested changes

2023-01-12 22:38 UTC, evanchia-ly-sdets commented on scripts/build/TestImpactAnalysis/test_impact/base_test_impact.py
> +            return
Might be useful to output something to log on return.

2023-01-12 22:38 UTC, evanchia-ly-sdets commented on scripts/build/TestImpactAnalysis/tiaf_driver.py
> +        help="Test suites to run",
Would be good to provide the list of suites or examples

2023-01-12 22:38 UTC, evanchia-ly-sdets commented on scripts/build/TestImpactAnalysis/tiaf_driver.py
> +        help="Test suite labels to exclude if matched",
Is this referring to CTest labels? Would be good to clarify

2023-01-12 23:45 UTC, Kadino commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage_local.py
> +                logger.error(f"Error copying tree '{source_directory}' to '{target_directory}'")
logger.exception is a handy way to log an error and automatically include stacktrace

2023-01-13 00:03 UTC, Kadino commented on scripts/build/Platform/Windows/build_config.json
> +      "CTEST_OPTIONS": "-L \"(SUITE_smoke|SUITE_main)\" -LE \"(REQUIRES_gpu|REQUIRES_tiaf)\" -T Test --no-tests=error",
This appears to remove all tests opting into TIAF from executing during Automated Review of pull requests. Has TIAF already been added into the pull request pipeline or was TIAF still executing in a separate pipeline?

No tests appear to be registered this way, so shipping this shouldn't cause an immediate outage.

2023-01-16 10:41 UTC, jonawals commented on scripts/build/TestImpactAnalysis/test_impact/base_test_impact.py
> +
Fixed 👍

2023-01-16 10:42 UTC, jonawals commented on scripts/build/TestImpactAnalysis/test_impact/base_test_impact.py
> +                    self._runtime_args.append(f"{argument.runtime_arg}{value}")
Fixed 👍

2023-01-16 10:48 UTC, jonawals commented on scripts/build/TestImpactAnalysis/test_impact/runtime_test_impact_args.py
> +    COMMON_LABEL_EXCLUDES = ("label_excludes", "--labelexcludes=", "Suite label excludes is set to: ")
As this will require a refactor across another project (tiaf runtime) I'll leave this for a followup PR 👍

2023-01-16 10:49 UTC, jonawals commented on scripts/build/TestImpactAnalysis/tiaf_driver.py
> +        required=False
Fixed 👍

2023-01-16 10:51 UTC, jonawals commented on scripts/build/TestImpactAnalysis/test_impact/base_test_impact.py
> +            return
Fixed 👍

2023-01-16 11:45 UTC, jonawals commented on scripts/build/TestImpactAnalysis/tiaf_driver.py
> +        help="Test suite labels to exclude if matched",
Fixed 👍

2023-01-16 11:47 UTC, jonawals commented on scripts/build/TestImpactAnalysis/tiaf_driver.py
> +        help="Test suites to run",
I'm not keen on putting specific suite examples as these aren't really TIAF specific. I think anyone using TIAF will be aware of what suites are available 👍

2023-01-16 15:28 UTC, jonawals commented on scripts/build/Platform/Windows/build_config.json
> +      "CTEST_OPTIONS": "-L \"(SUITE_smoke|SUITE_main)\" -LE \"(REQUIRES_gpu|REQUIRES_tiaf)\" -T Test --no-tests=error",
TIAF is now opt-in with the `REQUIRES_tiaf` test label (although no tests have this label yet) 👍

2023-01-18 17:41 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/Artifact/Factory/TestImpactTestTargetMetaMapFactoryUtils.cpp
> +        return labelSet.contains(RequiresTiafLabel) ? std::optional<SuiteLabelSet>{ labelSet } : AZStd::nullopt;
At the very least the std::optional should be `AZStd::optional`, especially since the second part of the ternary is using **AZStd**::nullopt
```suggestion
        return labelSet.contains(RequiresTiafLabel) ? AZStd::optional<SuiteLabelSet>{ labelSet } : AZStd::nullopt;
```

2023-01-18 17:41 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/Artifact/Factory/TestImpactTestTargetMetaMapFactoryUtils.cpp
> +            const auto labelString = label.GetString();
Extra whitetspace has been introduced on this line.
```suggestion
            const auto labelString = label.GetString();
```

2023-01-18 17:45 UTC, lumberyard-employee-dm commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage_s3.py
> +        @param suites_string: The concatenated test suites string for which the historic data will be obtained for.
This question is still not answered in the documentation.

As a user, what kind of this class, what is the format  they should use to passing in the suites_string variable.
An example would be good to indicated how the suite string should look.

2023-01-18 18:22 UTC, evanchia-ly-sdets approved these changes

2023-01-18 20:28 UTC, Kadino commented on scripts/build/Platform/Windows/build_config.json
> +      "CTEST_OPTIONS": "-L \"(SUITE_smoke|SUITE_main)\" -LE \"(REQUIRES_gpu|REQUIRES_tiaf)\" -T Test --no-tests=error",
Does opting in currently result in being run in a different job, or is that a future pending change?

2023-01-19 14:50 UTC, jonawals commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage_s3.py
> +        @param suites_string: The concatenated test suites string for which the historic data will be obtained for.
How the user interprets that is up to them. After all, it's just a key derived from the suites, the persistant storage has no concept of what suites other than this string will be used as a path segment to the bucket. The current user, the tiaf python scripts, concatenate the suites passed into it via the driver script with dash-separation.

2023-01-19 14:55 UTC, jonawals commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage_s3.py
> +        @param suites_string: The concatenated test suites string for which the historic data will be obtained for.
I could change the API doc for this to "The test suites string for which the historic data will be obtained for".

2023-01-19 16:24 UTC, lumberyard-employee-dm commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage_s3.py
> +        @param suites_string: The concatenated test suites string for which the historic data will be obtained for.
Ok, so this API looks like it has nothing do with with TestImpactAnalysisFramework and is a general S3 upload method, which we alre

2023-01-19 16:59 UTC, jonawals commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage.py
> +        @param suites_string:  The concatenated test suites string for which the historic data will be obtained for.
```suggestion
        @param suites_string: The unique key to differentiate the different suite combinations from one another different for which the historic data will be obtained for..
```

2023-01-19 17:02 UTC, lumberyard-employee-dm commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage.py
> +        @param suites_string:  The concatenated test suites string for which the historic data will be obtained for.
This clarification looks good.
It removes the ambiguity as to how to perform string concatenation and explains that the parameter only needs to be a unique identifier to segment historic data into a S3 bucket.

2023-01-19 17:05 UTC, lumberyard-employee-dm approved these changes

2023-01-19 17:09 UTC, spham-amzn approved these changes

2023-01-19 20:56 UTC, Kadino commented on cmake/TestImpactFramework/TestImpactTestTargetConfig.cmake
> +        list(REMOVE_ITEM TEST_LABELS REQUIRES_TIAF_LABEL)
It seems strange to remove the label even if the user has explicitly set it. Makes me a bit confused on how a customer would opt in to using TIAF, would they be invoking `o3de_test_impact_apply_test_labels ` on their test labels? My first impression was that opting in was as simple as the user setting `REQUIRES_tiaf` in their own labels, and that this was a configuration script that TIAF was running on their behalf. May want to more explicitly state intended usage in the function docstring (or other docs)

2023-01-19 20:56 UTC, Kadino commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage.py
> +        @param suites_string: The unique key to differentiate the different suite combinations from one another different for which the historic data will be obtained for.
minor: extra different `one another different for which` ==> `one another for which`

2023-01-19 20:56 UTC, Kadino commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage_s3.py
> +        @param suites_string: The concatenated test suites string for which the historic data will be obtained for.
Since it's not obvious, can this also be clearer about what a test suite is defined as? Are these CTest labels? CTest Module name plus labels? Individual test names? Is there an expected separator?

minor: there's a few extra words and tense changes, which can currently be simplified to:
`The unique key for unique suite combinations to obtain historic data for.`

2023-01-19 20:59 UTC, Kadino commented on scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage.py
> +        @param suites_string: The unique key to differentiate the different suite combinations from one another different for which the historic data will be obtained for.
Either copy the final docstring used by `__init__` of PersistentStorageS3 throughout this document, or else document that it is a passthrough to that class so the user reads that docstring.

2023-01-19 21:01 UTC, Kadino approved these changes
Given that my comments all recommend documentation improvements, I essentially approve of the code in this PR.

2023-01-19 22:39 UTC, jonawals commented on cmake/TestImpactFramework/TestImpactTestTargetConfig.cmake
> +        list(REMOVE_ITEM TEST_LABELS REQUIRES_TIAF_LABEL)
We need a way to be able to turn of TIAF for any reason. This flag allows TIAF to defer to CTest, should we ever need to flick the kill switch.

2023-01-23 08:56 UTC, merged