addressed feedback from commit e4823ad040 in branch ProjectExportCLIForScripts
aws-lumberyard-dev/o3de pull request #497
Opened 2023-03-08 03:18 UTC by tkothadev

This is a PR for the Project Export CLI with its first commit located here: https://github.com/aws-lumberyard-dev/o3de/commit/e4823ad04010972807f74812b1bc9849714e8ce1

Most of the code changes here are a second pass at the feedback provided at that commit link.

Unit testing is not yet implemented, but will likely come in the next commit, depending on feedback for the current PR.

Most notable change is the introduction of a second helper API: `execute_python_script`, which allows any user script to run a python script using the O3DE parameters defined in the CLI. Those parameters are now implemented as a singleton class `O3DEScriptExportParameters`, and attributes can be arbitrarily assigned to it. This allows for immense flexibility. The function also accepts arbitrary `**kwargs` and adds them as attributes to the export params singleton.

To help protect against overwriting important attributes, such as CLI parameters like`project-path`, and derailing the export process, such attributes are marked as read only. If the user needs to adjust this for other params in their script, they can use `mark_readonly_params` and `mark_writeable_params`.

Such introductions make the following python scripts possible:
```
#test_export.py
import os
import o3de.export_project as exp

from o3de.export_project import process_command, execute_python_script, O3DEScriptExportParameters

#we require users to instantiate the singleton class to make clear the origin point for export parameters
o3de_export = O3DEScriptExportParameters()

logger = o3de_export.logger

#one way of setting the export parameter is by attribute assignment. This will transfer to other scripts
# o3de_export.hi_there = "hi there!"

process_command(["cmake", "--version"])

#you can also set export parameters as kwargs in execute_python_script(). When this script is called, it can directly access the export parameters, and set new parameters as well, which can feed back in this script
execute_python_script("C:\\Users\\tkothadev\\Desktop\\hello.py", hi_there="hi there!")

logger.info(f"Now running the export code {o3de_export.project_path}")

logger.info(f"Engine path: {o3de_export.engine_path}")

#this is not defined in test_export.py. It comes from hello.py
logger.info(o3de_export.hello_back)

```

```
#hello.py
import o3de.export_project as exp
from o3de.export_project import O3DEScriptExportParameters
o3de_export = O3DEScriptExportParameters()

logger = o3de_export.logger

i = 0

while i < 10:
    print(f"hi {i}")
    i+=1

#this was defined by test_export.py
logger.info(o3de_export.hi_there)

print(o3de_export.project_path)
print(o3de_export.as_dict())

# this causes an error, since engine_path is read only
# o3de_export.engine_path = "whoops"

#we can set a variable that can be sent back to the script that executed us
o3de_export.hello_back = "Hello to you too!"

# we can leverage O3DE loggers from user scripts
logger.info("hi there!")

```
This is the resulting execution
```
λ .\scripts\o3de.bat export-project -es C:\workspace\projects\NewspaperDeliveryGame\export_rules\test_export.py --verbosity INFO hi there --gary
[INFO] o3de.export_project: Begin loading script 'test_export.py'...
[INFO] o3de.export_project: cmake version 3.24.1

[INFO] o3de.export_project:

[INFO] o3de.export_project: CMake suite maintained and supported by Kitware (kitware.com/cmake).

[INFO] o3de.export_project:
[INFO] o3de.export_project: Finishing current command...
[INFO] o3de.export_project: Begin loading script 'hello.py'...
hi 0
hi 1
hi 2
hi 3
hi 4
hi 5
hi 6
hi 7
hi 8
hi 9
[INFO] o3de.export_project: hi there!
C:\workspace\projects\NewspaperDeliveryGame
{'project_path': WindowsPath('C:/workspace/projects/NewspaperDeliveryGame'), 'engine_path': WindowsPath('C:/workspace/o3de'), 'logger': <Logger o3de.export_project (INFO)>, 'args': ['hi', 'there', '--gary'], 'hi_there': 'hi there!'}
[INFO] o3de.export_project: Now running the export code C:\workspace\projects\NewspaperDeliveryGame
[INFO] o3de.export_project: Engine path: C:\workspace\o3de
[INFO] o3de.export_project: Hello to you too!
[INFO] o3de.export_project: Finished exporting
```

2023-03-08 16:05 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +from o3de.validation import *
note: will change this from `import *` to `import valid_export_script, valid_o3de_project_path` before PR concludes

2023-03-08 16:16 UTC, AMZN-stankowi commented on scripts/o3de/o3de/validation.py
> +        logger.error("A Python script with .py extension must be supplied for --export-script parameter!")
I recommend adding the path that doesn't match here, to make the error a bit easier to follow.

"The --export-script parameter '{script_path}' does not have the extension py in the parameter. A Python script with .py extension must be supplied for --export-script parameter!"

2023-03-08 16:17 UTC, AMZN-stankowi approved these changes

2023-03-08 16:31 UTC, cgalvan approved these changes

2023-03-08 16:31 UTC, cgalvan commented on scripts/o3de/o3de/export_project.py
> +sys.path.insert(0, os.path.join(os.path.dirname(__file__),"..", "..","..","Tools","LyTestTools","ly_test_tools","environment"))
We shouldn't need this because using our o3de scripts should go through o3de's python, which has access to `LyTestTools` through egg-link.

2023-03-08 16:36 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +sys.path.insert(0, os.path.join(os.path.dirname(__file__),"..", "..","..","Tools","LyTestTools","ly_test_tools","environment"))
Really? how does that work w.r.t. import paths?

2023-03-08 16:42 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +READ_ONLY_PARAMS = ["export_script", "project_path", "engine_path", "logger", "args"]
I think that makes sense actually, since we expect the CLI parameters to never change. They would benefit from this approach.

2023-03-08 16:43 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +READ_ONLY_PARAMS = ["export_script", "project_path", "engine_path", "logger", "args"]
But, I would still keep the `mark_readonly_param` function as an option for user scripts. Teams may have their own parameters they want to consider readonly, and having this as an option is nice b/c it gives them the ability to add guard-rails for themselves.

2023-03-08 16:43 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +class O3DEScriptExportParameters(utils.BaseSingleton):
I'm not sure a singleton is necessary or really that useful here.  You could create an instance of this class in `export_project.py` and passed to the `export_script`. This will be more useful when writing your unit tests.  Singletons generally make testing more difficult and in this case I'm not sure I see the benefit.

2023-03-08 16:45 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +    logger = O3DEScriptExportParameters().logger
I think it's fine to use the existing `logger` created at the top of this file

2023-03-08 16:46 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +    if type(target_script_path) == str:
```suggestion
    if isinstance(target_script_path, str):
```

2023-03-08 16:53 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +        mark_readonly_params(LOGGER_PARAM)
What is the goal in creating our own logger, storing it in the export parameters and allowing it be overridden?  if you want to let the user control logging - could you just use the general logger which they can access and control using `logging`?

2023-03-08 16:53 UTC, lumberyard-employee-dm commented on scripts/o3de/o3de/export_project.py
> +sys.path.insert(0, os.path.join(os.path.dirname(__file__),"..", "..","..","Tools","LyTestTools","ly_test_tools","environment"))
This script can't use LyTestTools.
LyTestTools is used for testing the engine and is not part of the SDK layout, so this will not work for and SDK.
The functionality would have to be moved to the o3de packaage

2023-03-08 16:55 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +    logger.setLevel(args.log_level)
if you switch to the general logger this could be where you set the config:
```
logging.basicConfig( level=args.log_level.upper() )
```

2023-03-08 16:58 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +        mark_readonly_params(LOGGER_PARAM)
This came up while I was testing nested scripts, and I noticed that if you just use the single logger, it only comes from one source (export_project.py).

It makes it difficult to tell at a glance what the source of the log message was without reading the log for context. It is the same logger source regardless of the nested script you're in. With the override, it can change the log source, such that it reflects the script currently running
i.e. (`export_project.test_export`, `export_project.test_export.hello`, etc.) , and then `export_project` is reserved for lower level messages.

Upon second look, I'm also not sure allowing an override flag is a good idea. I am thinking to change it such that it always overrides the logger to display the name of the currently running script.

Would like second opinions on that though.

2023-03-08 17:01 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +sys.path.insert(0, os.path.join(os.path.dirname(__file__),"..", "..","..","Tools","LyTestTools","ly_test_tools","environment"))
I see. I will need to copy it to our utils package then

2023-03-08 17:03 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +    logger.info("Finished exporting")
I recommend not printing this statement, which could be interpreted as success, if there is an error

2023-03-08 17:04 UTC, lumberyard-employee-dm commented on scripts/o3de/o3de/export_project.py
> +class O3DEScriptExportParameters(utils.BaseSingleton):
Singletons are not a good pattern in general and tend to be misused. 
For one this unnecessary this restricts the use of this script within other python packages or tools.
For example if project manager wanted to export a project with the different set of parameters it can't do that in parallel and also would need to clear out an existing data. Such use cases that the user wanted to export a release layout for Linux and Windows, that wouldn't be able to be done.

2023-03-08 17:05 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +    main()
are you running this script outside of the o3de cli?

2023-03-08 17:06 UTC, AMZN-alexpete commented on scripts/o3de/o3de/validation.py
> +        logger.error(f"The export script '{script_path}' does not exist!")
nit, recommend not using exclamation marks in all the error logging, as it is a bit dramatic

2023-03-08 17:14 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +    logger.info("Finished exporting")
I feel it'd be better to have a statement like this in case the process is a success. Makes it easier to tell when things go smoothly. Perhaps instead I should check if the return code is a success, and only print if so.

2023-03-08 21:03 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +    main()
For unit tests I can see this happening. For instance i may need to invoke test scripts via CLI (or python approximation via sys module), to ensure the behavior is accurate.

2023-03-08 21:03 UTC, FuzzyCarterAWS commented on scripts/o3de/o3de/export_project.py
> +def execute_python_script(target_script_path: pathlib.Path or str, override_logger=False, **kwargs) -> int:
Additionally, `pathlib` is imported implicitly into this script from another imported file. Might want to make it explicitly imported in in case the child class that's using it ever changes behaviors.

2023-03-08 21:10 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +        while process.poll() is None:
Per the subprocess documentation: https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen.poll
None is returned if the child process has not terminated yet. Upon completion it will set and return the returncode (which I access later via `process.retcode`).

The suggested negation immediately terminates the loop, which is undesirable for fetching log statements during a running process.

2023-03-08 21:13 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +        logger.info("Finishing current command...")
That's a good question, and I'm not exactly sure how we want to tackle it. If we were to print the entire command, then that can sometimes involve spewing out very long command sequences (i.e. any non-trivial build command).

If we restrict it to just the first argument, which is most likely the executable, there can be issues as well. For instance, maybe the process actually runs cmake, but for some reason the command has to be fed through python or windows powershell (@allisaurus ran into this). Or the process involves multiple invocations of the same tool in a row. So showing that may not be very helpful.

That being said, I think at least showing the executable name (i.e. the first argument in the command list) is better than nothing.

2023-03-08 21:15 UTC, FuzzyCarterAWS reviewed
There's a lot of need for additional docstrings as well as flow comments/extracting responsibilities out of functions into their own areas of responsibility. Currently some of these functions can get extremely hard to follow and understand without a lot of scrolling back & forth due to their size & taking on too much responsibility.

2023-03-08 21:44 UTC, lumberyard-employee-dm commented on scripts/o3de/o3de/export_project.py
> +    script_name = os.path.basename(target_script_path)
What is the point of importing pathlib, if the code is just going to use the os.path functions?

My recommendation is that we still to using the [pathlib API](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module) and functions and don't try to support a hybrid string approach.

Strings aren't paths and subtlety always comes up with using string such as comparing two strings aren't the same as comparing two paths.
On Windows path comparison is case insensitive, while on non-Windows platforms it is case sensitive.
The pathlib always can deal with comparing paths with different slash directions where string comparison are too literal.
i.e `C:\foo` should be treated as equivlant to `C:/Foo` on Windows, which the pathlib library is meant to do.

2023-03-08 21:49 UTC, spham-amzn commented on scripts/o3de/o3de/export_project.py
> +            log_line = line.decode('utf-8')
Its possible to have utf-8 non-decodable bytes from stdout, which means if that occurs this will raise a decoding error. Unless the content is absolutely critical to be exact, you can have this ignore decoding errors like
```suggestion
            log_line = line.decode('utf-8', 'ignore')
```

2023-03-08 21:50 UTC, spham-amzn commented on scripts/o3de/o3de/export_project.py
> +        log_lines = process.stdout.read().decode('utf-8')
Same thing here regarding non-decodable bytes

2023-03-08 21:50 UTC, spham-amzn commented on scripts/o3de/o3de/export_project.py
> +        stderr = process.stderr.read()
Are we ignoring `stderr` ?

2023-03-08 21:51 UTC, spham-amzn commented on scripts/o3de/o3de/export_project.py
> +                logger_func(stderr.decode('utf-8'))
same decodable bytes issue here

2023-03-08 21:53 UTC, spham-amzn commented on scripts/o3de/o3de/export_project.py
> +        raise re
Not a fan of logging an error and re-raising it. If anything, the highect `except` block within the callstack should be doing the logging if its needed.

2023-03-08 21:58 UTC, lumberyard-employee-dm commented on scripts/o3de/o3de/export_project.py
> +                        help="Set the log verbosity level")
Normal verbose arguments are specified via multiple `-v` options such as `-v`, `-vv`, `-vvv`.
Users who are knowledgable with using CLI interfaces expect that to the convention.
The [argparse documentation](https://docs.python.org/3/library/argparse.html?highlight=argparse#action) even provides an example of using the verbose option
```python
parser = argparse.ArgumentParser()

parser.add_argument('--verbose', '-v', action='count', default=0)

parser.parse_args(['-vvv'])
Namespace(verbose=3)
```

2023-03-08 21:59 UTC, spham-amzn commented on scripts/o3de/o3de/export_project.py
> +        logger.error("Failed to process export script.")
based on the function name, shouldn't the error message read
```suggestion
        logger.error(f"Invalid export script path '{export_script_path}'.")
```

2023-03-08 22:12 UTC, spham-amzn commented
One comment in general is that there is a lot of doing a pattern of:

```
if (error):
    log.error(error)
    return 1
```
This can be cleaned up if we use exceptions and have a try: except: block in the main ` __name__ == "__main__" ` block. You can create a custom exception and just raise that, and have the main block handle that exception by logging the error message without the callstack, and then exiting with the error code

```
if __name__ == "__main__":
    do_something()
    exit(0)
except MyError as err:
    logger.error(err)
    exit(1)
```
If you reuse a more general `Exception` or 'RuntimeError`, then you may risk losing the callstack in the logger if you eat up that exception

2023-03-09 02:24 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +        mark_readonly_params(LOGGER_PARAM)
Yea on second thought, we can remove the nested logger logic for now. It feels out of scope for the current PR. If it's needed, it'd be better to have a dedicated review for it.

2023-03-09 02:25 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +    def get_project_path(args):
I can move it out to utils.py if it does not exist already.

2023-03-10 01:02 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +        raise re
Does that mean I should not log the error at this function, only raise it?

That would mean that the user scripts have to catch and log the scripts on their end. Ideally I would like for there to be as little friction as possible when using the API, which is why I opted to log the error here first.

2023-03-10 01:03 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +def execute_python_script(target_script_path: pathlib.Path or str, override_logger=False, **kwargs) -> int:
wait do you mean `pathlib` or `pathlib.Path`? Because the script directly imports `pathlib` at the top.

2023-03-10 02:48 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +        setattr(o3de_export, key, value)
I'm actually going to remove this. parameter tweaking should not happen in an execute script function.

2023-03-10 03:29 UTC, spham-amzn commented on scripts/o3de/o3de/export_project.py
> +                        help="Set the log verbosity level")
Actually, `-v`, `-vv`, and `-vvv` is a pretty standard convention for verbosity. `DEBUG`, 'INFO', 'ERROR', 'CRITICAL' is actually not verbosity, but log level, and has a different meaning. I'd suggest not using verbosity as the argument name here if that is the intent

2023-03-10 03:40 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +    logger.setLevel(args.log_level)
After switching to the general logger, I noticed that the log level did not behave as I expected. When I had log level set to INFO, it still only remained at ERROR level. For now I will keep the statement as is, but now it refers to the `logger` defined at the top of the script only, and nothing else.

2023-03-10 03:46 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +                        help="Set the log verbosity level")
@FuzzyCarterAWS I suspect you're right that there's opportunity to improve this. At present it is beyond the scope of the current PR, but worth creating a github issue to outline in detail.

2023-03-10 04:47 UTC, tkothadev commented
Updated code per recent commits now yield the following scripts:
```
#test_export.py
import os
import o3de.export_project as exp

from o3de.export_project import process_command, execute_python_script

#o3de_context is always injected into an export script before running
logger = o3de_context.logger

o3de_context.message1 = "This is a message!"
o3de_context.message2 = "___"

#users can use this to mark attributes in the context they do not wish to be changed
o3de_context.mark_readonly("message2")

#they can make such attributes writeable again using o3de_context.mark_writeable("...")

process_command(["cmake", "--version"])

o3de_context.set_params(hi_there="hi there!", hi_there_2=22)

execute_python_script("C:\\Users\\tankotha\\Desktop\\hello.py", o3de_context)

logger.info(f"Now running the export code {o3de_context.project_path}")

logger.info(f"Engine path: {o3de_context.engine_path}")

#this was set by hello.py
logger.info(o3de_context.hello_back)

#hello.py tried to set this, but was marked readonly
logger.info(o3de_context.message2)

```
```
#hello.py
import o3de.export_project as exp

logger = o3de_context.logger

i = 0

while i < 10:
    print(f"hi {i}:: {o3de_context.hi_there_2}")
    i+=1

logger.info(o3de_context.hi_there)
logger.info(o3de_context.message1)
print(o3de_context.project_path)
print(o3de_context.as_dict())

#user is unable to overwrite engine_path, it is logged as an error instead
o3de_context.engine_path = "whoops"

o3de_context.hello_back = "Hello to you too!"

#user set this value to readonly, so this overwrite will fail
o3de_context.message2 = "hiya!"
```

This is the resulting run:
```
λ .\scripts\o3de.bat export-project -es C:\workspace\projects\NewspaperDeliveryGame\export_rules\test_export.py -v INFO hi there --gary                           
[INFO] o3de.export_project: Begin loading script 'C:\workspace\projects\NewspaperDeliveryGame\export_rules\test_export.py'...                                     
[INFO] o3de.export_project: cmake version 3.24.1                                                                                                                  
                                                                                                                                                                  
[INFO] o3de.export_project:                                                                                                                                       
                                                                                                                                                                  
[INFO] o3de.export_project: CMake suite maintained and supported by Kitware (kitware.com/cmake).                                                                  
                                                                                                                                                                  
[INFO] o3de.export_project:                                                                                                                                       
[INFO] o3de.export_project: Finishing cmake...                                                                                                                    
[INFO] o3de.export_project: Begin loading script 'C:\Users\tankotha\Desktop\hello.py'...                                                                          
hi 0:: 22                                                                                                                                                         
hi 1:: 22                                                                                                                                                         
hi 2:: 22                                                                                                                                                         
hi 3:: 22                                                                                                                                                         
hi 4:: 22                                                                                                                                                         
hi 5:: 22                                                                                                                                                         
hi 6:: 22                                                                                                                                                         
hi 7:: 22                                                                                                                                                         
hi 8:: 22                                                                                                                                                         
hi 9:: 22                                                                                                                                                         
[INFO] o3de.export_project: hi there!                                                                                                                             
[INFO] o3de.export_project: This is a message!                                                                                                                    
C:\workspace\projects\NewspaperDeliveryGame                                                                                                                       
{'_read_only_names': {'_project_path', 'args', 'project_path', '_args', '_engine_path', 'engine_path', 'logger', '_read_only_attribute_names', '_export_script_pat
h', 'message2', 'export_script_path', '_logger'}, '_export_script_path': WindowsPath('C:/workspace/projects/NewspaperDeliveryGame/export_rules/test_export.py'), '
_project_path': WindowsPath('C:/workspace/projects/NewspaperDeliveryGame'), '_engine_path': WindowsPath('C:/workspace/o3de'), '_logger': <Logger o3de.export_proje
ct (INFO)>, '_args': ['hi', 'there', '--gary'], 'message1': 'This is a message!', 'message2': '___', 'hi_there': 'hi there!', 'hi_there_2': 22}                   
[ERROR] o3de.export_project: Cannot set 'engine_path' to 'whoops', it is a read-only parameter!                                                                   
[ERROR] o3de.export_project: Cannot set 'message2' to 'hiya!', it is a read-only parameter!                                                                       
[INFO] o3de.export_project: Now running the export code C:\workspace\projects\NewspaperDeliveryGame                                                               
[INFO] o3de.export_project: Engine path: C:\workspace\o3de                                                                                                        
[INFO] o3de.export_project: Hello to you too!                                                                                                                     
[INFO] o3de.export_project: ___                                                                                                                                   
```

2023-03-10 16:53 UTC, AMZN-stankowi commented on scripts/o3de/o3de/export_project.py
> +    if not project_path:
I find it's helpful to add a comment when you don't print an error, to help with maintenance. I was going to ask why this didn't log an error, but I saw that infer_project_path will log an error.

There is a difference in the behavior between validate_export_script and infer_project_path, though. One returns the reason and leaves the caller to report the error, the other reports the error internally.

I don't have a strong preference to either style, but I do prefer a codebase try to stick with one style of error management over mixing them.

2023-03-10 16:53 UTC, AMZN-stankowi commented on scripts/o3de/o3de/utils.py
> +            logger.debug("Unexpected exception ignored while terminating process, with stacktrace:", exc_info=True)
Is there a reason this is at debug level and not warning or error level? It feels like you would want unhandled exceptions to make it to the log output at the end, even if you didn't have a very verbose setting enabled.

2023-03-10 18:31 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +    if not project_path:
noted, I will probably change it to prefer returning the error reason instead. That way the caller can use their preferred logger

2023-03-10 18:32 UTC, tkothadev commented on scripts/o3de/o3de/utils.py
> +            logger.debug("Unexpected exception ignored while terminating process, with stacktrace:", exc_info=True)
The main reason is because I took the code directly from ly_test_tools process_utils and moved it over here. I opted to not change the code at the time, but I think here it makes sense to change the logger to issue warnings/errors instead.

2023-03-10 18:42 UTC, spham-amzn commented on scripts/o3de/o3de/utils.py
> +            logger.debug("Unexpected exception ignored while terminating process, with stacktrace:", exc_info=True)
I also think in the case of a broad exception, you should at least capture the exception log that error out (and omit the callstack if that was the intention here).
```
except Exception as err:
    logger.error(f"Unexpected exception {err} .....")
```

2023-03-10 18:56 UTC, allisaurus commented on scripts/o3de/o3de/export_project.py
>  def process_command(args: list,
similar to `safe_kill_processes` and the validation methods, this feels like it should be extracted as separate utility class or at least a util func (though the fact it includes child funcs tips my preference towards structuring it as a class)

2023-03-10 19:04 UTC, FuzzyCarterAWS approved these changes
Some nit picky improvements suggested.

Additionally, I noticed a function or two that could use a docstring or another comment due to complexity but was not necessary.

2023-03-10 19:04 UTC, FuzzyCarterAWS commented on scripts/o3de/o3de/utils.py
> +            logger.warning("Termination request ignored, process was already terminated during iteration with stacktrace:", exc_info=True)
NIT: If this in-line def can be moved before the if-statement that'd helped with readability and flow.

2023-03-10 19:17 UTC, spham-amzn commented on scripts/o3de/o3de/utils.py
> +        logger.error(f"Failed to run script '{script_path}': \nException: "+ str(re))
1. In general its not a good idea to do multi-line logging because loggers use the severity (DEBUG, INFO, ERROR, etc) at the header of each logger line. Adding a `\n` will look like 
```
[ERROR] Failed to run script 'foo'
Exception: bar
```
These headers are commonly used to perform greps of logs for error identification, so this information would be missed in those cases

2. No need to do `str(re)`. The default `__str__` operator should be invoked if you just do `{re}`.

2023-03-10 19:19 UTC, spham-amzn commented on scripts/o3de/o3de/utils.py
> +def add_to_system_path(path: pathlib.Path):
This assumes that `path` is a path to a file?

2023-03-10 19:21 UTC, spham-amzn commented on scripts/o3de/o3de/export_project.py
> +        target_script_path = pathlib.Path(target_script_path)
You could probably move this conversion to `Path` in the `add_to_system_path` instead of outside of it so this line wouldnt be needed

2023-03-10 19:27 UTC, spham-amzn commented on scripts/o3de/o3de/utils.py
> +def infer_project_path(target_file_path: pathlib.Path, supplied_project_path: pathlib.Path = None) -> Tuple[pathlib.Path or None, str]:
This should raise exceptions on error and return the project path if not an error instead of this pattern. To the caller, its simpler to do:
```
   try:
       project_path = infer_project_path(....)
   except Exception as err:
      logger.error(str(err))
      return 1
```

2023-03-10 20:20 UTC, cgalvan approved these changes

2023-03-10 20:22 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +        target_script_path = pathlib.Path(target_script_path)
`load_and_execute_script` also needs `Path`. I can provide the conversion for both though.

2023-03-10 21:28 UTC, FuzzyCarterAWS approved these changes
This is fantastic.

A little clarity suggestions here, but otherwise, this is super easy to follow and extendable.

2023-03-10 21:28 UTC, FuzzyCarterAWS commented on scripts/o3de/o3de/utils.py
> +class CLICommand(object):
NIT: Add a docstring here to clearly define the class's purpose and its responsibilities.

2023-03-10 21:28 UTC, FuzzyCarterAWS commented on scripts/o3de/o3de/utils.py
> +def infer_project_path(target_file_path: pathlib.Path, supplied_project_path: pathlib.Path = None) -> pathlib.Path:
NIT: Use a name here that's easier to discover `get_project_path_from_file`?

2023-03-10 22:22 UTC, FuzzyCarterAWS approved these changes

2023-03-10 22:50 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +    main()
Do you mean PyTests? The o3de modules use PyTests and should not need any `main` function defined - see `compatibility.py` and `test_compatibility.py` for an example of this.

2023-03-10 23:25 UTC, AMZN-alexpete requested changes

2023-03-10 23:25 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +        return self.__dict__
I'm not a fan of this unnecessary complexity - I really think you should start as simple as possible and not add this readonly/writeable and as_dict() functionality until you have a solid use case that needs it.

2023-03-10 23:25 UTC, AMZN-alexpete commented on scripts/o3de/o3de/validation.py
> +    return True
Having a validation function for a path seems unnecessary when you can use the existing `valid_o3de_project_json` to check the path and if the file exists, I think this function should also be removed.

2023-03-10 23:25 UTC, AMZN-alexpete commented on scripts/o3de/o3de/validation.py
> +    return True
I don't think this complexity is needed to verify a file exists for a function that is likely only ever to be used once by the o3de export command.  I think this should be removed - and I think we should keep the pattern of validation functions returning True or False and letting the caller raise an exception or handle the error in a way that makes sense to them.

2023-03-10 23:25 UTC, AMZN-alexpete commented on scripts/o3de/o3de/validation.py
> +from typing import Tuple
This import is not used and should be removed

2023-03-11 00:16 UTC, lumberyard-employee-dm commented on scripts/o3de/o3de/validation.py
> +    return True
I agree, a validate function is something the caller is voluntary calling to verify some constraint, so it would be unexpected that call to a function that performs validation throws an exception.

2023-03-11 00:20 UTC, lumberyard-employee-dm commented on scripts/o3de/o3de/export_project.py
> +        return self.__dict__
We need to keep in mind of who the customer is for this script.

This isn't a production script, that is invoked by untrusted users. 
This is a script used by a development for creating a layout of artifacts they need to distribute their project.

I am not seeing the threat model that the readonly properties are meant to protect against.

2023-03-11 00:26 UTC, lumberyard-employee-dm commented on scripts/o3de/o3de/utils.py
> +            raise valid.InvalidProjectPathException(f"Unable to find project folder associated with file '{target_file_path}'. Please specify using --project-path, or ensure the file is inside a proj
There is nothing about this function I believe should throw an exception.

As this is a utility function, it can just `return None` if the target path isn't under the project.

By throwing the exception, the function is expecting in the normal call patterns that the target_file_path is always underneath a project_path, which doesn't seem like a reasonable expectation for a utilty.

This intent of this function seems more to return the project_root if it a file is underneath the project, other return none.

2023-03-11 01:21 UTC, tkothadev commented on scripts/o3de/o3de/utils.py
> +            raise valid.InvalidProjectPathException(f"Unable to find project folder associated with file '{target_file_path}'. Please specify using --project-path, or ensure the file is inside a proj
I would like to retain relevant error messages, because it can help troubleshoot what is missing.
Would you be okay with a convention where the function returns a tuple of the result and a string encapsulating the error message (if any)?

If not, what would you recommend for relaying error messages? Should that be handled by this function, or the caller?

2023-03-11 01:36 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +        return self.__dict__
I'd be fine with a simple dictionary, but I can see how having a class object with `@property` members with python docs would make it easier for users to discover and get information about those properties in their IDE.

2023-03-11 03:19 UTC, tkothadev commented on scripts/o3de/o3de/validation.py
> +    return True
On that note, I'm removing it as a helper function, because it's too specific for checking export scripts. I do not see it being useful outside of that context.

2023-03-14 02:01 UTC, lumberyard-employee-dm commented on scripts/o3de/o3de/utils.py
> +def add_to_system_path(file_path: pathlib.Path or str) -> None:
You may want to name this function prepend_to_system_path.
`add_to_system_path` implies it is being added to the end.
Which does have an impact on importing a module(for example if the user have their own module module called `utils`, they would want to know which order to call `add_to_system_path` in.

2023-03-14 02:08 UTC, lumberyard-employee-dm commented on scripts/o3de/o3de/export_project.py
> +                        help="Set the log verbosity level")
I don't agree with going against established convention of developers.
A good command line interface is one that is familiar to users and within their expectation.

As mentioned in this Atlassian blog post, their number 1 principle is [Align with established conventions](https://blog.developer.atlassian.com/10-design-principles-for-delightful-clis/)

2023-03-14 23:41 UTC, lumberyard-employee-dm commented on scripts/o3de/o3de/utils.py
> +            raise valid.InvalidProjectPathException(f"Unable to find project folder associated with file '{target_file_path}'. Please specify using --project-path, or ensure the file is inside a proj
The tuple convention works, and would be inline with how we use AZ::Outcome(std::expected) in C++.

My point here is that some of depending on the operation the function is meant to perform some of the actions aren't errors.
For example if the caller invokes a a function to open a file at path `<project-path>/foo`, could be an error that can throw an exception if the file doesn't exist.
But if the caller is invoking a function to find the nearest ancestor project path from a source path, then not finding the path isn't an error, it is within the expectation of the function.

2023-03-15 15:45 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +                        help="Set the log verbosity level")
Although I understand the reason to not go against established convention (since it can risk mental friction with expectations), I will state here that I do not agree with the convention or standard itself.

I only state this because `--verbosity DEBUG / -v DEBUG` or `--verbosity INFO / -v INFO` is much clearer and obvious to me than `-v` `-vv` to mean the same thing. At the end of the day, I desire clarity more than convention.

That being said, if it is a common enough convention with standard mapping of meaning as @spham-amzn pointed out, then I'm able to agree to disagree, and go with the standard. That being said I will add relevant helper text to clarify what `-v`, `-vv`, and `-vvv` actually do. 

This is not redundant information, because before this PR I was not aware such a convention exists, and I suspect other O3DE users may experience the same gap.

2023-03-15 18:11 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +    :param cwd: The desired current working directory of the command. Useful for commands which require a differing starting environment.
```suggestion
    :param cwd: The desired current working directory of the command. Useful for commands which require a differing starting environment.
    :param env: Optional environment to use when processing this command.
```

2023-03-15 18:21 UTC, AMZN-alexpete commented on scripts/o3de/o3de/export_project.py
> +                        help="Set the log verbosity level")
You could also include a `--log-level` argument that sets the log level by names like `DEBUG`, `INFO` in addition to the 'verbosity' argument that uses the `-v -vv`  convention.

2023-03-15 18:24 UTC, AMZN-alexpete commented on scripts/o3de/o3de/utils.py
> +            raise err
why are we catching the exception and then raising it again?  Did you want to log the error before raising it?

2023-03-15 18:28 UTC, AMZN-alexpete commented on scripts/o3de/o3de/utils.py
> +    :param processes: An iterable of processes to kill
```suggestion
    :param processes: An iterable of processes to kill
    :param process_logger: (Optional) logger to use 
```

2023-03-15 18:36 UTC, AMZN-alexpete approved these changes
Just some minor missing doc comments and suggestions.

2023-03-16 00:23 UTC, tkothadev commented on scripts/o3de/o3de/utils.py
> +            raise err
That is the intent, but I missed writing the code that did it. But one question I have here is if there's a better way to do this.

I feel it's different from printing stderr, because that comes only from the subprocess itself. The logs here would catch any other error state, using python exceptions.

2023-03-16 01:08 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +                        help="Set the log verbosity level")
that would be a good compromise here. I can convert the existing `verbosity` parameter to be `log-level` instead.

2023-03-16 01:11 UTC, tkothadev commented on scripts/o3de/o3de/export_project.py
> +                        help="Set the log verbosity level")
but on that note, re-reading @spham-amzn's comments, perhaps verbosity is the incorrect term for this. I'm thinking we should just stick with `log-level`, because that is what the user is actually tweaking when running the script.

2023-03-16 01:32 UTC, tkothadev commented
There has been sufficient review on this PR, and there is majority consensus among requested reviewers. Feedback has also narrowed into minor details (which is a good sign). All current feedback has been addressed, and rermaining parties have stated they have no further feedback for the PR. As such I am merging changes into the branch. Any follow up items will be for a new PR.

2023-03-16 01:33 UTC, merged