Initial commit.
aws-lumberyard-dev/o3de pull request #510
Opened 2023-03-29 16:24 UTC by jonawals

## What does this PR do?

_Please describe your PR. For a bug fix, what was the old behavior, what is the new behavior?_

_Please add links to any issues, RFCs or other items that are relevant to this PR._

## How was this PR tested?

_Please describe any testing performed._

2023-03-30 09:36 UTC, hultonha approved these changes
Overall looks good, one question I have is is it still possible to disable sharding if you're trying to diagnose a failure (to rule out if it is somehow caused by the sharding or not). So long as that's still possible with these changes I think this is a solid improvement.

2023-03-30 09:36 UTC, hultonha commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Include/TestImpactFramework/Native/TestImpactNativeRuntimeConfigurationFactory.h
> + */
update: Missing `#pragma once`

2023-03-30 09:36 UTC, hultonha commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestEngine/Native/TestImpactNativeTestEngine.cpp
> +        const AZStd::vector<const NativeTestTarget*> testTargets) const
update: Looks like this should be passed by const ref (missing `&`)

2023-03-30 09:36 UTC, hultonha commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestEngine/Native/TestImpactNativeTestEngine.h
> +        AZStd::vector<TestTargetAndEnumeration> GenerateTestTargetAndEnumerations(const AZStd::vector<const NativeTestTarget*> testTargets) const;
update: Missing `&` for vector parameter

2023-03-30 09:36 UTC, hultonha commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.cpp
> +            const auto shardCoverageArtifact = GenerateShardedTargetCoverageArtifactFilePath(testTarget, i);
nit: `shard` -> `sharded`

2023-03-30 09:36 UTC, hultonha commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.h
> +            jobId += jobInfos.back().GetJobInfos().size();
question: Would be useful to add a comment why this is used for `jobId` - why are we adding the job infos size each time?

2023-03-30 09:36 UTC, hultonha commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Shard/TestImpactNativeShardedTestJob.h
> +        StdContent m_std;
suggestion: Member comments could be useful here

2023-03-30 09:36 UTC, hultonha commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Shard/TestImpactNativeShardedTestJob.h
> +            // doesn't make a great deal of sense to try and consolodate the jobs at this level anyway (the completed
nit: consolidate

2023-03-30 16:17 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/Target/Native/TestImpactNativeTestTarget.cpp
> +        inline constexpr auto GTest = "FRAMEWORK_googletest";
This type should be set to a `const char*` to be explicit about the type.
Also would deduce this type to a `const char[X]`
```suggestion
        inline constexpr const char* GTest = "FRAMEWORK_googletest";
```

2023-03-30 16:19 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestEngine/Native/TestImpactNativeTestEngine.cpp
> +        const AZStd::vector<const NativeTestTarget*> testTargets) const
Alternatively a `AZStd::span<const NativeTestTarget*>` can be accepted by value.
The removes the needed to construct a temporary vector, when a vector does not exist at the call site.
```suggestion
        AZStd::span<const NativeTestTarget*> testTargets) const
```

2023-03-30 16:32 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.cpp
> +            AZStd::string::format("%zu%s", shardNumber, artifactFilePath.Extension().String().c_str()).c_str());
A DynamicMemory allocations can be avoided here by using the `AZ_STRING_ARG` instead of `String()` with `%.*s` argument.
Also the final `.c_str()` isn't needed. An AZStd::string_view can be made directly
```suggestion
        return artifactFilePath.ReplaceExtension(
            AZStd::string_view(AZStd::string::format("%zu%.*s", shardNumber, AZ_STRING_ARG(artifactFilePath.Extension().Native()).Native()));
```

2023-03-30 17:29 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.h
> +    };
This specializations cost a lot more compile time than adding a member function to the class that is `operator<` and a `operator size_t`.

Plus the TestTargetAndEnumeration `operator<` can be implemented in a cpp file, saving compile time
```suggestion
    bool TestImpact::TestTargetAndEnumeration::operator<(const TestImpact::TestTargetAndEnumeration& other) const
    {
        return reinterpret_cast<size_t>(this->first) < reinterpret_cast<size_t>(other.first);
    }

    //! Hash function for TestTargetAndEnumeration types for use in unordered maps and sets.
    size_t TestImpact::operator size_t() const noexcept
    {
        return reinterpret_cast<size_t>(this->first);
    }
```

2023-03-30 17:32 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Shard/TestImpactNativeShardedTestRunnerBase.h
> +                const size_t subStringLength = AZStd::min(size_t{ 500 }, jobData->m_std.m_out->length());
500 is a magic number here and not explained at all what it is for.

2023-03-30 17:36 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeTestRunJobData.h
> +        NativeTestRunJobData& operator=(NativeTestRunJobData&& other);
These functions can be = defaulted.
All the implementations do is the same thing the default copy/move constructor and assignment operators would do.
```suggestion
        //! Copy and move constructors/assignment operators.
        NativeTestRunJobData(const NativeTestRunJobData& other) = default;
        NativeTestRunJobData(NativeTestRunJobData&& other) = default;
        NativeTestRunJobData& operator=(const NativeTestRunJobData& other) = default;
        NativeTestRunJobData& operator=(NativeTestRunJobData&& other) = default;
```

2023-03-30 17:37 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeTestJobInfoUtils.cpp
> +    typename NativeRegularTestRunner::Command GenerateRegularTestJobInfoCommand(
Repeat: typename is not needed here.
```suggestion
    NativeTestEnumerator::Command GenerateTestEnumeratorJobInfoCommand(
        const AZStd::string& launchArguement, const RepoPath& runArtifact)
    {
        const auto regularCommand = GenerateRegularTestJobInfoCommand(launchArguement, runArtifact);
        return { AZStd::string::format("%s --gtest_list_tests", regularCommand.m_args.c_str()) };
    }

    NativeRegularTestRunner::Command GenerateRegularTestJobInfoCommand(
```

2023-03-30 17:37 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeTestJobInfoUtils.h
> +    typename NativeRegularTestRunner::Command GenerateRegularTestJobInfoCommand(
repeat: typename is not needed here.
```suggestion
    NativeTestEnumerator::Command GenerateTestEnumeratorJobInfoCommand(
        const AZStd::string& launchArguement, const RepoPath& runArtifact);

    //! Generates a regular test run job command.
    NativeRegularTestRunner::Command GenerateRegularTestJobInfoCommand(
```

2023-03-30 17:41 UTC, lumberyard-employee-dm requested changes

2023-03-30 17:41 UTC, lumberyard-employee-dm commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeTestRunJobData.h
> +    }
This code can't compile.
GetLaunchMethod is not a member function.
Also it is already implemented inside of the `NativeTestRunJobData` template class.

2023-03-30 19:43 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestEngine/Native/TestImpactNativeTestEngine.cpp
> +        const AZStd::vector<const NativeTestTarget*> testTargets) const
Fixed 👍

2023-03-30 19:44 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.cpp
> +            const auto shardCoverageArtifact = GenerateShardedTargetCoverageArtifactFilePath(testTarget, i);
Fixed 👍

2023-03-30 19:46 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.h
> +            jobId += jobInfos.back().GetJobInfos().size();
Fixed 👍

2023-03-30 19:47 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Shard/TestImpactNativeShardedTestJob.h
> +        StdContent m_std;
Fixed 👍

2023-03-30 19:53 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.cpp
> +            AZStd::string::format("%zu%s", shardNumber, artifactFilePath.Extension().String().c_str()).c_str());
Fixed (with fixing of syntax) 👍

2023-03-30 19:54 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.h
> +    };
I'll leave this comment as unresolved and will address in the staging branch as this will span more than this PR 👍

2023-03-30 19:54 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Shard/TestImpactNativeShardedTestRunnerBase.h
> +                const size_t subStringLength = AZStd::min(size_t{ 500 }, jobData->m_std.m_out->length());
It's in the API comment, but I've added it here as well to clarify 👍

2023-03-30 19:56 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeTestRunJobData.h
> +        NativeTestRunJobData& operator=(NativeTestRunJobData&& other);
Fixed 👍

2023-03-30 19:56 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeTestRunJobData.h
> +    }
Fixed 👍

2023-03-30 20:33 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Include/TestImpactFramework/Native/TestImpactNativeRuntimeConfigurationFactory.h
> + */
Fixed 👍

2023-03-30 20:43 UTC, jonawals commented on Code/Tools/TestImpactFramework/Runtime/Native/Code/Include/TestImpactFramework/Native/TestImpactNativeRuntimeConfigurationFactory.h
> + */
I have no idea why this is still showing as not having my changes when locally it does and I've pushed everything 😵‍💫

2023-03-31 10:06 UTC, merged

2023-03-31 10:12 UTC, amzn-ahmadkrm reviewed
LGTM!